export default {
  appDEFields: [
    {
      codeName: 'createman',
      logicName: '创建人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATEMAN',
      id: 'createman',
    },
    {
      codeName: 'updateman',
      logicName: '最后更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATEMAN',
      id: 'updateman',
    },
    {
      codeName: 'orgid',
      logicName: '组织标识',
      predefinedType: 'ORGID',
      stdDataType: 25,
      stringLength: 100,
      name: 'ORGID',
      id: 'orgid',
    },
    {
      codeName: 'userid',
      logicName: '用户标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USERID',
      id: 'userid',
    },
    {
      codeName: 'openuserid',
      logicName: '第三方用户标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'OPENUSERID',
      id: 'openuserid',
    },
    {
      codeName: 'mobile',
      logicName: '手机',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MOBILE',
      id: 'mobile',
    },
    {
      codeName: 'openusername',
      logicName: '第三方用户名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      enableQuickSearch: true,
      name: 'OPENUSERNAME',
      id: 'openusername',
    },
    {
      codeName: 'open_type',
      logicName: '第三方用户类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OPEN_TYPE',
      id: 'open_type',
    },
    {
      codeName: 'openusercode',
      logicName: '第三方用户代码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OPENUSERCODE',
      id: 'openusercode',
    },
    {
      codeName: 'isbinding',
      logicName: '是否绑定',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ISBINDING',
      id: 'isbinding',
    },
    {
      codeName: 'depts',
      logicName: '部门',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPTS',
      id: 'depts',
    },
    {
      codeName: 'createdate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATEDATE',
      id: 'createdate',
    },
    {
      codeName: 'updatedate',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATEDATE',
      id: 'updatedate',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'openuserDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'createman',
          logicName: '创建人',
          appDEFieldId: 'createman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'createman',
        },
        {
          codeName: 'updateman',
          logicName: '最后更新人',
          appDEFieldId: 'updateman',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'updateman',
        },
        {
          codeName: 'orgid',
          logicName: '组织标识',
          appDEFieldId: 'orgid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'orgid',
        },
        {
          codeName: 'userid',
          logicName: '用户标识',
          appDEFieldId: 'userid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'userid',
        },
        {
          codeName: 'openuserid',
          logicName: '第三方用户标识',
          appDEFieldId: 'openuserid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'openuserid',
        },
        {
          codeName: 'mobile',
          logicName: '手机',
          appDEFieldId: 'mobile',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile',
        },
        {
          codeName: 'openusername',
          logicName: '第三方用户名称',
          appDEFieldId: 'openusername',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'openusername',
        },
        {
          codeName: 'open_type',
          logicName: '第三方用户类型',
          appDEFieldId: 'open_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'open_type',
        },
        {
          codeName: 'openusercode',
          logicName: '第三方用户代码',
          appDEFieldId: 'openusercode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'openusercode',
        },
        {
          codeName: 'isbinding',
          logicName: '是否绑定',
          appDEFieldId: 'isbinding',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'isbinding',
        },
        {
          codeName: 'depts',
          logicName: '部门',
          appDEFieldId: 'depts',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'depts',
        },
        {
          codeName: 'createdate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'createdate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'createdate',
        },
        {
          codeName: 'updatedate',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'updatedate',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'updatedate',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'openuserDTO',
      id: 'openuserdto',
    },
    {
      codeName: 'openuserFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_OPENUSERID_EQ',
          logicName: '第三方用户标识',
          appDEFieldId: 'openuserid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_OPENUSERID_EQ',
          id: 'n_openuserid_eq',
        },
        {
          codeName: 'N_OPEN_TYPE_EQ',
          logicName: '第三方用户类型',
          appDEFieldId: 'open_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_OPEN_TYPE_EQ',
          id: 'n_open_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'openuserFilterDTO',
      id: 'openuserfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'openuserid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'OPENUSERID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'openuserid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'OPENUSERID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchWxwork',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'openuserfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'openuserdto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchwxwork',
      actionType: 'REMOTE',
      dataSetName: 'wxwork',
      dataSetTag: 'wxwork',
      dataSetType: 'REMOTE',
      name: 'FetchWxwork',
      id: 'fetchwxwork',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'openuser',
  deapicodeName: 'openuser',
  deapicodeName2: 'openusers',
  deapitag: 'OPENUSER',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'openuserid',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.OPENUSER',
  },
  logicName: '第三方用户',
  majorAppDEFieldId: 'openusername',
  orgIdAppDEFieldId: 'orgid',
  quickSearchAppDEFieldIds: ['openusername'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'OPENUSER',
  id: 'plmweb.openuser',
  codeName2: 'openusers',
  requestPaths: [],
};
