export default {
  appDEFields: [
    {
      codeName: 'change_type',
      logicName: '变更类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CHANGE_TYPE',
      id: 'change_type',
    },
    {
      codeName: 'principal_id',
      logicName: '关联主体标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      codeName: 'change_version',
      logicName: '变更版本',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CHANGE_VERSION',
      id: 'change_version',
    },
    {
      codeName: 'owner_type',
      logicName: '所属数据对象',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      codeName: 'principal_type',
      logicName: '关联主体类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      codeName: 'stage_results',
      logicName: '评审结果',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'STAGE_RESULTS',
      id: 'stage_results',
    },
    {
      codeName: 'target_type',
      logicName: '关联目标类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TYPE',
      id: 'target_type',
    },
    {
      codeName: 'final_stage_results',
      logicName: '最终评审结果',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FINAL_STAGE_RESULTS',
      id: 'final_stage_results',
    },
    {
      codeName: 'target_version_id',
      logicName: '目标对象版本标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_VERSION_ID',
      id: 'target_version_id',
    },
    {
      codeName: 'parent_version_id',
      logicName: '父对象版本标识',
      predefinedType: 'PARENTVERSIONID',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_VERSION_ID',
      id: 'parent_version_id',
    },
    {
      codeName: 'review_data',
      logicName: '评审数据',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'REVIEW_DATA',
      id: 'review_data',
    },
    {
      codeName: 'test_case',
      logicName: '测试用例',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TEST_CASE',
      id: 'test_case',
    },
    {
      codeName: 'idea',
      logicName: '产品需求',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'IDEA',
      id: 'idea',
    },
    {
      codeName: 'cur_version_id',
      logicName: '当前版本标识',
      predefinedType: 'VERSIONID',
      stdDataType: 25,
      stringLength: 100,
      name: 'CUR_VERSION_ID',
      id: 'cur_version_id',
    },
    {
      codeName: 'target_identifier',
      logicName: '目标对象编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_IDENTIFIER',
      id: 'target_identifier',
    },
    {
      codeName: 'target_title',
      logicName: '目标对象标题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TITLE',
      id: 'target_title',
    },
    {
      codeName: 'target_state',
      logicName: '目标对象状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_STATE',
      id: 'target_state',
    },
    {
      codeName: 'target_assignee',
      logicName: '目标对象负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ASSIGNEE',
      id: 'target_assignee',
    },
    {
      codeName: 'target_version',
      logicName: '关联目标版本',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TARGET_VERSION',
      id: 'target_version',
    },
    {
      codeName: 'target_priority',
      logicName: '目标对象优先级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PRIORITY',
      id: 'target_priority',
    },
    {
      codeName: 'target_parent_id',
      logicName: '目标对象父标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PARENT_ID',
      id: 'target_parent_id',
    },
    {
      codeName: 'target_id',
      logicName: '关联目标标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ID',
      id: 'target_id',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_MAN',
      },
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'create_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_TIME',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_MAN',
      },
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'update_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.UPDATE_TIME',
      },
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
  ],
  appDELogics: [
    {
      codeName: 'nothing',
      defaultParamName: 'Default',
      logicName: '无操作',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'plmweb.review_content',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      enableFront: true,
      valid: true,
      name: '无操作',
      id: 'nothing',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'review_content_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'change_type',
          logicName: '变更类型',
          appDEFieldId: 'change_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'change_type',
        },
        {
          codeName: 'principal_id',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_id',
        },
        {
          codeName: 'change_version',
          logicName: '变更版本',
          appDEFieldId: 'change_version',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          listMap: true,
          id: 'change_version',
        },
        {
          codeName: 'owner_type',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_type',
        },
        {
          codeName: 'principal_type',
          logicName: '关联主体类型',
          appDEFieldId: 'principal_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_type',
        },
        {
          codeName: 'stage_results',
          logicName: '评审结果',
          appDEFieldId: 'stage_results',
          refAppDEMethodDTOId: 'review_result_dto',
          refAppDataEntityId: 'plmweb.review_result',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'stage_results',
        },
        {
          codeName: 'final_stage_results',
          logicName: '最终评审结果',
          appDEFieldId: 'final_stage_results',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'final_stage_results',
        },
        {
          codeName: 'target_type',
          logicName: '关联目标类型',
          appDEFieldId: 'target_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_type',
        },
        {
          codeName: 'parent_version_id',
          logicName: '父对象版本标识',
          appDEFieldId: 'parent_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_version_id',
        },
        {
          codeName: 'target_version_id',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_version_id',
        },
        {
          codeName: 'review_data',
          logicName: '评审数据',
          appDEFieldId: 'review_data',
          refAppDEMethodDTOId: 'review_dto',
          refAppDataEntityId: 'plmweb.review',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'review_data',
        },
        {
          codeName: 'idea',
          logicName: '产品需求',
          appDEFieldId: 'idea',
          refAppDEMethodDTOId: 'idea_dto',
          refAppDataEntityId: 'plmweb.idea',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'idea',
        },
        {
          codeName: 'test_case',
          logicName: '测试用例',
          appDEFieldId: 'test_case',
          refAppDEMethodDTOId: 'test_case_dto',
          refAppDataEntityId: 'plmweb.test_case',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'test_case',
        },
        {
          codeName: 'cur_version_id',
          logicName: '当前版本标识',
          appDEFieldId: 'cur_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cur_version_id',
        },
        {
          codeName: 'target_identifier',
          logicName: '目标对象编号',
          appDEFieldId: 'target_identifier',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_identifier',
        },
        {
          codeName: 'target_title',
          logicName: '目标对象标题',
          appDEFieldId: 'target_title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_title',
        },
        {
          codeName: 'target_state',
          logicName: '目标对象状态',
          appDEFieldId: 'target_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_state',
        },
        {
          codeName: 'target_assignee',
          logicName: '目标对象负责人',
          appDEFieldId: 'target_assignee',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_assignee',
        },
        {
          codeName: 'target_version',
          logicName: '关联目标版本',
          appDEFieldId: 'target_version',
          refAppDEMethodDTOId: 'version_dto',
          refAppDataEntityId: 'plmweb.version',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'target_version',
        },
        {
          codeName: 'target_priority',
          logicName: '目标对象优先级',
          appDEFieldId: 'target_priority',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_priority',
        },
        {
          codeName: 'target_parent_id',
          logicName: '目标对象父标识',
          appDEFieldId: 'target_parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_parent_id',
        },
        {
          codeName: 'target_id',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_id',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'review_content_dto',
    },
    {
      codeName: 'review_content_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_principal_id_eq',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_principal_id_eq',
        },
        {
          codeName: 'n_target_id_eq',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_id_eq',
        },
        {
          codeName: 'n_target_version_id_eq',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_version_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'review_content_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_review_content',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_review_content',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_review_content',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'complete_review',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/complete_review',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'complete_review',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'create_review_data',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/create_review_data',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'create_review_data',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'nothing',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        name: 'NothingInput',
        id: 'nothinginput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'NothingResult',
        id: 'nothingresult',
      },
      actionMode: 'CUSTOM',
      actionType: 'DELOGIC',
      appDELogicId: 'nothing',
      dataSetType: 'REMOTE',
      id: 'nothing',
    },
    {
      codeName: 'program_test_case',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      requestPath: '/program_test_case',
      needResourceKey: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'program_test_case',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'review_content_total',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/review_content_total',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'review_content_total',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'set_review_result',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/set_review_result',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'set_review_result',
    },
    {
      codeName: 'set_review_result_all',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/set_review_result_all',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'set_review_result_all',
    },
    {
      codeName: 'start_review',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/start_review',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'start_review',
    },
    {
      codeName: 'submit_review',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/submit_review',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'submit_review',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      sysPFPluginId: 'review_content_sort',
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_cur_history',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_history',
      actionType: 'REMOTE',
      dataSetName: 'cur_history',
      dataSetTag: 'cur_history',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_history',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_history_list',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_history_list',
      actionType: 'REMOTE',
      dataSetName: 'history_list',
      dataSetTag: 'history_list',
      dataSetType: 'REMOTE',
      id: 'fetch_history_list',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '返回',
      codeName: 'back',
      frontProcessType: 'OTHER',
      fullCodeName: 'review_content_back',
      tooltip: '返回',
      uiactionMode: 'FRONT',
      uiactionTag: 'back',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'back',
      appDataEntityId: 'plmweb.review_content',
      name: '返回',
      id: 'back@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '完成评审',
      codeName: 'complete_review',
      frontProcessType: 'WIZARD',
      fullCodeName: 'review_content_complete_review',
      appDEMethodId: 'update',
      uiactionMode: 'FRONT',
      uiactionTag: 'complete_review',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'complete_cur_stage_review',
      appDataEntityId: 'plmweb.review_content',
      name: '完成当前阶段评审',
      id: 'complete_review@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '评审',
      codeName: 'complete_review_quickly',
      dataAccessAction: 'UPDATE',
      frontAppViewId: 'plmweb.review_content_result_option_view',
      fullCodeName: 'review_content_complete_review_quickly',
      appDEMethodId: 'set_review_result_all',
      deopprivId: 'review__update',
      refreshMode: 1,
      successMsg: '评审已完成',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'complete_review_quickly',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDataEntityId: 'plmweb.review_content',
      name: '快速评审',
      id: 'complete_review_quickly@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '返回',
      codeName: 'panel_usr0612818719_button_calluilogic_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'review_content_panel_usr0612818719_button_calluilogic_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_usr0612818719_button_calluilogic_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'back_history',
      appDataEntityId: 'plmweb.review_content',
      name: '返回',
      id: 'panel_usr0612818719_button_calluilogic_click@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '规划需求',
      codeName: 'program_review_idea',
      frontAppViewId: 'plmweb.idea_review_re_idea_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'review_content_program_review_idea',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'program_review_idea',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'get_review_data',
      appDataEntityId: 'plmweb.review_content',
      name: '规划评审需求',
      id: 'program_review_idea@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '规划用例',
      codeName: 'program_review_test_case',
      frontAppViewId: 'plmweb.test_case_mpick_up_view2_review',
      frontProcessType: 'WIZARD',
      fullCodeName: 'review_content_program_review_test_case',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'program_review_test_case',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'get_review_data',
      appDataEntityId: 'plmweb.review_content',
      name: '规划评审用例',
      id: 'program_review_test_case@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移出用例',
      codeName: 'remove_case',
      confirmMsg: '确定移除该用例？',
      dataAccessAction: 'UPDATE',
      fullCodeName: 'review_content_remove_case',
      appDEMethodId: 'remove',
      deopprivId: 'update',
      sysImage: {
        cssClass: 'fa fa-mail-reply',
        glyph: 'xf112@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '移除成功',
      timeout: 60000,
      tooltip: '移出',
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove_case',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDataEntityId: 'plmweb.review_content',
      name: '移出用例',
      id: 'remove_case@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移出用例',
      codeName: 'remove_case_all',
      confirmMsg: '确定移除该用例？',
      fullCodeName: 'review_content_remove_case_all',
      appDEMethodId: 'remove',
      sysImage: {
        cssClass: 'fa fa-mail-reply',
        glyph: 'xf112@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '移除成功',
      timeout: 60000,
      tooltip: '移出',
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove_case_all',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.review_content',
      name: '移出用例（无权限）',
      id: 'remove_case_all@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '版本比对',
      codeName: 'review_content_version_comparison',
      frontProcessType: 'OTHER',
      fullCodeName: 'review_content_review_content_version_comparison',
      sysImage: {
        cssClass: 'fa fa-exchange',
        glyph: 'xf0ec@FontAwesome',
      },
      tooltip: '版本比对',
      uiactionMode: 'FRONT',
      uiactionTag: 'review_content_version_comparison',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'review_content_version_comparison',
      appDataEntityId: 'plmweb.review_content',
      name: '评审内容版本比对',
      id: 'review_content_version_comparison@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '设置评审结果',
      codeName: 'set_review_result',
      dataAccessAction: 'SUBDATA',
      frontProcessType: 'OTHER',
      fullCodeName: 'review_content_set_review_result',
      appDEMethodId: 'set_review_result',
      deopprivId: 'subdata',
      successMsg: '评审结果已设置',
      uiactionMode: 'FRONT',
      uiactionTag: 'set_review_result',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDEUILogicId: 'open_result',
      appDataEntityId: 'plmweb.review_content',
      name: '设置评审结果',
      id: 'set_review_result@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '开始评审',
      codeName: 'start_cur_stage_review',
      confirmMsg: '是否开始当前阶段评审',
      frontProcessType: 'OTHER',
      fullCodeName: 'review_content_start_cur_stage_review',
      appDEMethodId: 'update',
      refreshMode: 1,
      successMsg: '已开启',
      uiactionMode: 'FRONT',
      uiactionTag: 'start_cur_stage_review',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'start_cur_stage_review',
      appDataEntityId: 'plmweb.review_content',
      name: '开始当前阶段评审',
      id: 'start_cur_stage_review@review_content',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '提交评审',
      codeName: 'submit_review',
      dataAccessAction: 'UPDATE',
      frontProcessType: 'OTHER',
      fullCodeName: 'review_content_submit_review',
      appDEMethodId: 'submit_review',
      deopprivId: 'review__update',
      navigateParams: [
        {
          key: 'review',
          value: 'review',
          id: 'review',
        },
      ],
      paramItem: 'review',
      refreshMode: 2,
      uiactionMode: 'FRONT',
      uiactionTag: 'submit_review',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDEUILogicId: 'commit_review',
      appDataEntityId: 'plmweb.review_content',
      name: '提交评审',
      id: 'submit_review@review_content',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'back',
      defaultParamName: 'Default',
      logicName: '返回',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parent_form',
              paramAction: 'BINDPARAM',
              srcFieldName: 'layoutPanel.panelItems.form',
              srcDEUILogicParamId: 'parentview',
              srcValueType: 'SRCDLPARAM',
              name: 'parentView[layoutPanel.panelItems.form] ==> parent_form',
              id: 'parentview[layoutpanel.panelitems.form] ==> parent_form',
            },
          ],
          topPos: 410,
          name: '绑定表单',
          id: 'preparejsparam2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parentview',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parentView',
              id: 'view[parentview] ==> parentview',
            },
          ],
          topPos: 310,
          name: '获取父视图对象',
          id: 'preparejsparam1',
        },
        {
          code: 'uiLogic.parent_form.control.details.grouppanel6.state.visible=true;\r\nuiLogic.parent_form.control.details.review_results.state.keepAlive=true;\r\nuiLogic.parent_form.control.details.review_results.state.visible=false;\r\n\r\nconst choose_data = uiLogic.parent_form.control.details.choosed_content;\r\nchoose_data.setDataValue(null);',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          topPos: 520,
          name: '切换显示组件',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'parent_form',
          entityParam: true,
          name: '父表单',
          id: 'parent_form',
        },
        {
          codeName: 'parentView',
          entityParam: true,
          name: 'parentView',
          id: 'parentview',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '返回',
      id: 'back',
    },
    {
      codeName: 'back_history',
      defaultParamName: 'Default',
      logicName: '返回（历史）',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'uiLogic.parentview.ctx.controllersMap.get("form").details.grouppanel8.state.visible=true;\r\nuiLogic.parentview.ctx.controllersMap.get("form").details.grouppanel11.state.visible=false;\r\n',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'viewctrlinvoke1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 510,
          name: '切换显示组件',
          id: 'rawjscode1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parentview',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parentView',
              id: 'view[parentview] ==> parentview',
            },
          ],
          topPos: 310,
          name: '获取父视图对象',
          id: 'preparejsparam1',
        },
        {
          invokeCtrlId: 'form',
          invokeMethod: 'load',
          invokeParamId: 'default',
          codeName: 'VIEWCTRLINVOKE1',
          leftPos: 160,
          logicNodeType: 'VIEWCTRLINVOKE',
          topPos: 630,
          name: '表单刷新',
          id: 'viewctrlinvoke1',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'form',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.form.control',
              srcDEUILogicParamId: 'parentview',
              srcValueType: 'SRCDLPARAM',
              name: 'parentView[layoutPanel.panelItems.form.control] ==> form',
              id: 'parentview[layoutpanel.panelitems.form.control] ==> form',
            },
          ],
          topPos: 410,
          name: '绑定表单',
          id: 'preparejsparam2',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'parentView',
          entityParam: true,
          name: 'parentView',
          id: 'parentview',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'form',
          ctrlParam: true,
          name: '表单',
          id: 'form',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '返回（历史）',
      id: 'back_history',
    },
    {
      codeName: 'calc_column_action_state',
      defaultParamName: 'Default',
      logicName: '计算表格列行为状态(review)',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 260,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "const rows = uiLogic.grid.state.rows;\r\nif (rows && rows.length > 0) {\r\n\trows.forEach(row => {\r\n\t\tconst titleColumn = row.uiActionGroupStates.target_title;\r\n\t\tconst review_state = row.data.review_data.state;\r\n\t\tif (titleColumn && Object.values(titleColumn).length > 0) {\r\n\t\t\tObject.values(titleColumn).forEach(action => {\r\n\t\t\t\tif (action.uiActionId === 'remove_case@review_content') {\r\n\t\t\t\t\taction.visible = review_state == '10';\r\n\t\t\t\t}\r\n                if(action.uiActionId === 'remove_case@review_content' && context.srfreadonly ==true){\r\n                    action.visible = false;\r\n                }\r\n\t\t\t})\r\n\t\t}\r\n        row.editColStates.change_type.disabled = review_state == '60';\r\n        row.editColStates.change_version.disabled = review_state == '60';\r\n        row.editColStates.change_version.readonly = review_state == '60';\r\n        row.editColStates.change_version.editable = review_state == '60';\r\n\t})\r\n}\r\n",
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 410,
          name: '计算表格列行为状态',
          id: 'rawjscode1',
        },
        {
          codeName: 'END1',
          leftPos: 200,
          logicNodeType: 'END',
          topPos: 571,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'grid',
          leftPos: 160,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 490,
          name: '设置后的表格',
          id: 'debugparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Grid',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '计算表格列行为状态(review)',
      id: 'calc_column_action_state',
    },
    {
      codeName: 'commit_review',
      defaultParamName: 'Default',
      logicName: '提交评审',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -130,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'review',
                    dstLogicParamId: 'ctx',
                    logicType: 'SINGLE',
                    name: 'ctx[review] 值不为空(NotNil)',
                    id: 'ctx[review] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '表单内',
            },
            {
              dstDEUILogicNodeId: 'deaction1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'review',
                    dstLogicParamId: 'ctx',
                    logicType: 'SINGLE',
                    name: 'ctx[review] 值为空(Nil)',
                    id: 'ctx[review] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '表格上',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: -170,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parent_view',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parent_view',
              id: 'view[parentview] ==> parent_view',
            },
            {
              dstDEUILogicParamId: 'parent_form',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.form.control',
              srcDEUILogicParamId: 'parent_view',
              srcValueType: 'SRCDLPARAM',
              name: 'parent_view[layoutPanel.panelItems.form.control] ==> parent_form',
              id: 'parent_view[layoutpanel.panelitems.form.control] ==> parent_form',
            },
          ],
          topPos: 458,
          name: '准备参数',
          id: 'preparejsparam1',
        },
        {
          code: 'const choose_data = uiLogic.parent_form.details.choosed_content;\r\nchoose_data.setDataValue(null);\r\nuiLogic.parent_form.details.grouppanel6.state.keepAlive=true;\r\nuiLogic.parent_form.details.grouppanel6.state.visible=true;\r\nuiLogic.parent_form.details.review_results.state.visible=false;',
          codeName: 'RAWJSCODE2',
          leftPos: 30,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction1',
              srcDEUILogicNodeId: 'rawjscode2',
              id: '连接名称',
            },
          ],
          topPos: 458,
          name: '注入脚本代码',
          id: 'rawjscode2',
        },
        {
          code: "ibiz.mc.command.update.send({ srfdecodename: 'review', srfkey: context.review})",
          codeName: 'RAWJSCODE1',
          leftPos: 546,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '通知刷新',
          id: 'rawjscode1',
        },
        {
          dstAppDEActionId: 'submit_review',
          dstAppDataEntityId: 'plmweb.review_content',
          codeName: 'DEACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 359,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'deaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '实体行为',
          id: 'deaction1',
        },
        {
          codeName: 'END1',
          leftPos: 798,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'parent_view',
          entityParam: true,
          name: '父视图',
          id: 'parent_view',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'parent_form',
          entityParam: true,
          name: '父表单',
          id: 'parent_form',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '提交评审',
      id: 'commit_review',
    },
    {
      codeName: 'complete_cur_stage_review',
      defaultParamName: 'Default',
      logicName: '完成当前阶段评审',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 30,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'const choose_data = uiLogic.parent_form.details.choosed_content;\r\nchoose_data.setDataValue(null);\r\n// uiLogic.parent_form.details.grouppanel6.state.keepAlive=true;\r\nuiLogic.parent_form.details.grouppanel6.state.visible=true;\r\n// uiLogic.parent_form.details.review_results.state.keepAlive=true;\r\nuiLogic.parent_form.details.review_results.state.visible=false;\r\n',
          codeName: 'RAWJSCODE4',
          leftPos: 521,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction1',
              srcDEUILogicNodeId: 'rawjscode4',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '默认显示阶段列表，隐藏评审结果',
          id: 'rawjscode4',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 131,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'msgbox1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'curstage_id',
              dstDEUILogicParamId: 'default',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'curstage_id',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              name: 'ctx[curstage_id] ==> Default[curstage_id]',
              id: 'ctx[curstage_id] ==> default[curstage_id]',
            },
            {
              dstDEUILogicParamId: 'parent_view',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parent_view',
              id: 'view[parentview] ==> parent_view',
            },
            {
              dstDEUILogicParamId: 'parent_form',
              paramAction: 'BINDPARAM',
              srcFieldName: 'layoutPanel.panelItems.form.control',
              srcDEUILogicParamId: 'parent_view',
              srcValueType: 'SRCDLPARAM',
              name: 'parent_view[layoutPanel.panelItems.form.control] ==> parent_form',
              id: 'parent_view[layoutpanel.panelitems.form.control] ==> parent_form',
            },
          ],
          topPos: 208,
          name: '获取阶段数据与父标识',
          id: 'preparejsparam1',
        },
        {
          code: 'const need_refresh = uiLogic.parent_form.details.need_refresh;\r\nneed_refresh.setDataValue(true);',
          codeName: 'RAWJSCODE2',
          leftPos: 910,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode3',
              srcDEUILogicNodeId: 'rawjscode2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '为主表单设置值',
          id: 'rawjscode2',
        },
        {
          dstAppDEActionId: 'complete_review',
          dstAppDataEntityId: 'plmweb.review_content',
          codeName: 'DEACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 714,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '完成评审',
          id: 'deaction1',
        },
        {
          code: "ibiz.mc.command.update.send({ srfdecodename: 'review', srfkey: context.review})",
          codeName: 'RAWJSCODE3',
          leftPos: 1124,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode3',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '通知刷新',
          id: 'rawjscode3',
        },
        {
          code: "uiLogic.parent_form.details.druipart2.embedView.call('Refresh')",
          codeName: 'RAWJSCODE1',
          leftPos: 860,
          logicNodeType: 'RAWJSCODE',
          topPos: 470,
          name: '通过call刷新',
          id: 'rawjscode1',
        },
        {
          buttonsType: 'OKCANCEL',
          message:
            '请确认当前阶段所有评审已完成，完成评审后无法再对评审数据进行修改',
          msgBoxType: 'WARNING',
          codeName: 'MSGBOX1',
          leftPos: 317,
          logicNodeType: 'MSGBOX',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode4',
              srcDEUILogicNodeId: 'msgbox1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '消息弹窗',
          id: 'msgbox1',
        },
        {
          codeName: 'END1',
          leftPos: 1340,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图',
          id: 'view',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
        {
          codeName: 'parent_form',
          entityParam: true,
          name: '父表单',
          id: 'parent_form',
        },
        {
          codeName: 'parent_view',
          entityParam: true,
          name: '父页面',
          id: 'parent_view',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '完成当前阶段评审',
      id: 'complete_cur_stage_review',
    },
    {
      codeName: 'get_review_content_total',
      defaultParamName: 'Default',
      logicName: '获取评审内容总条数',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 70,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          dstAppDEActionId: 'get',
          dstAppDataEntityId: 'plmweb.review_content',
          codeName: 'DEACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 160,
          logicNodeType: 'DEACTION',
          topPos: 350,
          name: '获取评审结果进度',
          id: 'deaction1',
        },
        {
          codeName: 'END1',
          leftPos: 200,
          logicNodeType: 'END',
          topPos: 561,
          name: '结束',
          id: 'end1',
        },
        {
          code: 'const total = uiLogic.ctrl.state.total;\r\nconst rows = uiLogic.grid.state.rows;\r\nuiLogic.view.layoutPanel.state.data.total = rows.length;\r\nif (rows && rows.length > 0) {\r\n    let total_already = 0;\r\n    rows.forEach(row => {\r\n        const state = row.data.final_stage_results;\r\n    if (state !== null && state !== undefined) {\r\n        total_already++;\r\n    }\r\n    });\r\n    uiLogic.view.layoutPanel.state.data.total_already = total_already;\r\n    const floatTotal = parseFloat(rows.length);\r\n    const floatTotalAlready = parseFloat(total_already);\r\n    const ratio = Math.round((floatTotalAlready / floatTotal) * 100); \r\n    uiLogic.view.layoutPanel.state.data.schedule = ratio;\r\n} else {\r\n    uiLogic.view.layoutPanel.state.data.total_already = 0;\r\n    uiLogic.view.layoutPanel.state.data.schedule = 0;\r\n}\r\n',
          codeName: 'RAWJSCODE1',
          leftPos: -180,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 320,
          name: '设置总条数',
          id: 'rawjscode1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'curstage_id',
              dstDEUILogicParamId: 'default',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'curstage_id',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              name: 'ctx[curstage_id] ==> Default[curstage_id]',
              id: 'ctx[curstage_id] ==> default[curstage_id]',
            },
          ],
          topPos: 190,
          name: '准备参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
        {
          codeName: 'VIEW',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'CTRL',
          activeCtrlParam: true,
          ctrlParam: true,
          name: '当前部件对象',
          id: 'ctrl',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '获取评审内容总条数',
      id: 'get_review_content_total',
    },
    {
      codeName: 'get_review_data',
      defaultParamName: 'Default',
      logicName: '获取评审数据',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -130,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'END1',
          leftPos: 570,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'default',
          leftPos: 39,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          code: "const appDataEntityId = 'plmweb.review_content';\r\nconst context = uiLogic.ctx;\r\nconst data_arr = uiLogic.default;\r\n\r\nconst keyMapping = {\r\n    srfkey: 'target_id',\r\n};\r\n\r\nconst propertyMap = uiLogic.view.model.appViewParams?.find(\r\n    item => item.key.toLowerCase() === 'PROPERTYMAP'.toLowerCase(),\r\n);\r\n\r\nif (propertyMap) {\r\n    const keyValuePairs = propertyMap.value.split(',');\r\n    // 遍历键值对数组并添加到 keyMapping 映射对象中\r\n    for (const pair of keyValuePairs) {\r\n        const [sourceKey, targetKey] = pair.split(':');\r\n        if (sourceKey && targetKey) {\r\n            keyMapping[sourceKey] = targetKey;\r\n        }\r\n    }\r\n}\r\n\r\n// *转换属性\r\nconst addData = data_arr.map(item => {\r\n    const tempData = {};\r\n    // 遍历映射对象，将属性从 item 复制到 tempData\r\n    Object.keys(keyMapping).forEach(key => {\r\n        const targetKey = keyMapping[key];\r\n        tempData[targetKey] = item[key];\r\n    });\r\n    // 获取 change_version 中 from 对象的 owner_type\r\n    const ownerType = context.principal_type.toUpperCase();\r\n    // 将 target_type 字段设置为 owner_type\r\n    tempData['target_type'] = ownerType;\r\n    keyMapping['srfkey'] = item['id'];\r\n    return tempData;\r\n});\r\n\r\n// 获取实体服务并调用创建接口\r\nconst service = ibiz.hub.getApp(context.srfappid).deService;\r\nservice.exec(appDataEntityId, 'Create', context, addData);\r\n",
          codeName: 'RAWJSCODE1',
          leftPos: 296,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityListParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          id: 'view',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '应用上下文',
          id: 'ctx',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '获取评审数据',
      id: 'get_review_data',
    },
    {
      codeName: 'open_result',
      defaultParamName: 'Default',
      logicName: '打开评审结果',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -370,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'const choose_data = uiLogic.parent_form.control.details.choosed_content;\r\nchoose_data.setDataValue(uiLogic.default.id);\r\nuiLogic.parent_form.control.details.grouppanel6.state.keepAlive=true;\r\nuiLogic.parent_form.control.details.grouppanel6.state.visible=false;\r\nuiLogic.parent_form.control.details.review_results.state.visible=true;',
          codeName: 'RAWJSCODE2',
          leftPos: 283,
          logicNodeType: 'RAWJSCODE',
          topPos: 208,
          name: '注入脚本代码',
          id: 'rawjscode2',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'cur_container',
          leftPos: -270,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 210,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: -86,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'parent_view',
              paramAction: 'BINDPARAM',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parent_view',
              id: 'view[parentview] ==> parent_view',
            },
            {
              dstDEUILogicParamId: 'parent_form',
              paramAction: 'BINDPARAM',
              srcFieldName: 'layoutPanel.panelItems.form',
              srcDEUILogicParamId: 'parent_view',
              srcValueType: 'SRCDLPARAM',
              name: 'parent_view[layoutPanel.panelItems.form] ==> parent_form',
              id: 'parent_view[layoutpanel.panelitems.form] ==> parent_form',
            },
          ],
          topPos: 208,
          name: '绑定父视图及表单',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'cur_container',
          activeContainerParam: true,
          name: '当前容器对象',
          id: 'cur_container',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'choosed_content',
          entityParam: true,
          name: '选择的内容',
          id: 'choosed_content',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'parent_form',
          entityParam: true,
          name: '父表单',
          id: 'parent_form',
        },
        {
          codeName: 'parent_view',
          entityParam: true,
          name: '父视图',
          id: 'parent_view',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '打开评审结果',
      id: 'open_result',
    },
    {
      codeName: 'review_content_version_comparison',
      defaultParamName: 'Default',
      logicName: '评审内容版本比对',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 40,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'debugparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 250,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM4',
          leftPos: 550,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam4',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'review_content',
              paramAction: 'COPYPARAM',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default ==> review_content',
              id: 'default ==> review_content',
            },
          ],
          topPos: 258,
          name: '准备参数',
          id: 'preparejsparam4',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 1132,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'test_case',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcValueType: 'NONEVALUE',
              name: '无值（NONE） ==> ctx[test_case]',
              id: '无值（none） ==> ctx[test_case]',
            },
            {
              dstFieldName: 'idea',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcValueType: 'NONEVALUE',
              name: '无值（NONE） ==> ctx[idea]',
              id: '无值（none） ==> ctx[idea]',
            },
          ],
          topPos: 258,
          name: '准备参数',
          id: 'preparejsparam2',
        },
        {
          codeName: 'END1',
          leftPos: 1375,
          logicNodeType: 'END',
          topPos: 250,
          name: '结束',
          id: 'end1',
        },
        {
          codeName: 'DEBUGPARAM1',
          dstDEUILogicParamId: 'default',
          leftPos: 137,
          logicNodeType: 'DEBUGPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    groupOP: 'OR',
                    deuilogicLinkConds: [
                      {
                        condOP: 'EQ',
                        dstFieldName: 'principal_type',
                        dstLogicParamId: 'ctx',
                        paramValue: 'test_case',
                        value: 'test_case',
                        logicType: 'SINGLE',
                        id: 'ctx[principal_type] 等于(=) test_case',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'target_type',
                        dstLogicParamId: 'default',
                        paramValue: 'TEST_CASE',
                        value: 'TEST_CASE',
                        logicType: 'SINGLE',
                        name: 'Default[target_type] 等于(=) TEST_CASE',
                        id: 'default[target_type] 等于(=) test_case',
                      },
                    ],
                    logicType: 'GROUP',
                    name: 'OR',
                    id: 'or',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    groupOP: 'OR',
                    deuilogicLinkConds: [
                      {
                        condOP: 'EQ',
                        dstFieldName: 'target_type',
                        dstLogicParamId: 'default',
                        paramValue: 'IDEA',
                        value: 'IDEA',
                        logicType: 'SINGLE',
                        name: 'Default[target_type] 等于(=) IDEA',
                        id: 'default[target_type] 等于(=) idea',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'principal_type',
                        dstLogicParamId: 'ctx',
                        paramValue: 'idea',
                        value: 'idea',
                        logicType: 'SINGLE',
                        id: 'ctx[principal_type] 等于(=) idea',
                      },
                    ],
                    logicType: 'GROUP',
                    name: 'OR',
                    id: 'or',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'debugparam1',
              id: '连接名称',
            },
          ],
          topPos: 258,
          name: '调试逻辑参数',
          id: 'debugparam1',
        },
        {
          dstAppDEUIActionId: 'review_content_version_comparison@version',
          dstAppDataEntityId: 'plmweb.version',
          codeName: 'DEUIACTION1',
          dstDEUILogicParamId: 'review_content',
          leftPos: 940,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'deuiaction1',
              id: '连接名称',
            },
          ],
          topPos: 180,
          name: '界面行为',
          id: 'deuiaction1',
        },
        {
          code: "const review_content = uiLogic.review_content;\r\nconst content_version = review_content.change_version;\r\n\r\n\r\nif(content_version && content_version.length >0){\r\n    content_version.forEach((c_version, index) => {\r\n        if(c_version.srflistmapfield == 'from'){\r\n            review_content.base_version = c_version.id;\r\n        }\r\n        if(c_version.srflistmapfield == 'to'){\r\n            review_content.compare_version = c_version.id;\r\n        }\r\n    })\r\n\r\n}\r\n\r\n",
          codeName: 'RAWJSCODE1',
          leftPos: 741,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deuiaction1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    groupOP: 'OR',
                    deuilogicLinkConds: [
                      {
                        condOP: 'EQ',
                        dstFieldName: 'target_type',
                        dstLogicParamId: 'default',
                        paramValue: 'TEST_CASE',
                        value: 'TEST_CASE',
                        logicType: 'SINGLE',
                        name: 'Default[target_type] 等于(=) TEST_CASE',
                        id: 'default[target_type] 等于(=) test_case',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'principal_type',
                        dstLogicParamId: 'ctx',
                        paramValue: 'test_case',
                        value: 'test_case',
                        logicType: 'SINGLE',
                        id: 'ctx[principal_type] 等于(=) test_case',
                      },
                    ],
                    logicType: 'GROUP',
                    name: 'OR',
                    id: 'or',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
            {
              dstDEUILogicNodeId: 'deuiaction2',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    groupOP: 'OR',
                    deuilogicLinkConds: [
                      {
                        condOP: 'EQ',
                        dstFieldName: 'target_type',
                        dstLogicParamId: 'default',
                        paramValue: 'IDEA',
                        value: 'IDEA',
                        logicType: 'SINGLE',
                        name: 'Default[target_type] 等于(=) IDEA',
                        id: 'default[target_type] 等于(=) idea',
                      },
                      {
                        condOP: 'EQ',
                        dstFieldName: 'principal_type',
                        dstLogicParamId: 'ctx',
                        paramValue: 'idea',
                        value: 'idea',
                        logicType: 'SINGLE',
                        id: 'ctx[principal_type] 等于(=) idea',
                      },
                    ],
                    logicType: 'GROUP',
                    name: 'OR',
                    id: 'or',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 258,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
        {
          dstAppDEUIActionId: 'idea_review_content_version_comparison@version',
          dstAppDataEntityId: 'plmweb.version',
          codeName: 'DEUIACTION2',
          dstDEUILogicParamId: 'review_content',
          leftPos: 940,
          logicNodeType: 'DEUIACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'deuiaction2',
              id: '连接名称',
            },
          ],
          topPos: 326,
          name: '界面行为',
          id: 'deuiaction2',
        },
        {
          codeName: 'PREPAREJSPARAM3',
          leftPos: 370,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam4',
              srcDEUILogicNodeId: 'preparejsparam3',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'idea',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'target_id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[target_id] ==> ctx[idea]',
              id: 'default[target_id] ==> ctx[idea]',
            },
          ],
          topPos: 326,
          name: '准备参数',
          id: 'preparejsparam3',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 370,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam4',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'test_case',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'target_id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[target_id] ==> ctx[test_case]',
              id: 'default[target_id] ==> ctx[test_case]',
            },
          ],
          topPos: 190,
          name: '准备参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'review_content',
          entityParam: true,
          name: '评审内容',
          id: 'review_content',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '评审内容版本比对',
      id: 'review_content_version_comparison',
    },
    {
      codeName: 'start_cur_stage_review',
      defaultParamName: 'Default',
      logicName: '开始当前阶段评审',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -90,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'const need_refresh = uiLogic.parent_form.details.need_refresh;\r\nneed_refresh.setDataValue(true);',
          codeName: 'RAWJSCODE2',
          leftPos: 703,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'rawjscode2',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '注入脚本代码',
          id: 'rawjscode2',
        },
        {
          buttonsType: 'OKCANCEL',
          message: '确定开始当前阶段的评审吗？',
          msgBoxType: 'QUESTION',
          title: '评审',
          codeName: 'MSGBOX1',
          leftPos: 332,
          logicNodeType: 'MSGBOX',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction1',
              srcDEUILogicNodeId: 'msgbox1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '消息弹窗',
          id: 'msgbox1',
        },
        {
          codeName: 'END1',
          leftPos: 1120,
          logicNodeType: 'END',
          topPos: 200,
          name: '结束',
          id: 'end1',
        },
        {
          code: "ibiz.mc.command.update.send({ srfdecodename: 'review', srfkey: context.review})",
          codeName: 'RAWJSCODE1',
          leftPos: 895,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '通知刷新',
          id: 'rawjscode1',
        },
        {
          dstAppDEActionId: 'start_review',
          dstAppDataEntityId: 'plmweb.review_content',
          codeName: 'DEACTION1',
          dstDEUILogicParamId: 'default',
          leftPos: 513,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction1',
              id: '连接名称',
            },
          ],
          topPos: 208,
          name: '实体行为',
          id: 'deaction1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 31,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'msgbox1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'curstage_id',
              dstDEUILogicParamId: 'default',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'curstage_id',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              name: 'ctx[curstage_id] ==> Default[curstage_id]',
              id: 'ctx[curstage_id] ==> default[curstage_id]',
            },
            {
              dstDEUILogicParamId: 'parent_view',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'parentView',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[parentView] ==> parent_view',
              id: 'view[parentview] ==> parent_view',
            },
            {
              dstDEUILogicParamId: 'parent_form',
              paramAction: 'BINDPARAM',
              srcFieldName: 'layoutPanel.panelItems.form.control',
              srcDEUILogicParamId: 'parent_view',
              srcValueType: 'SRCDLPARAM',
              name: 'parent_view[layoutPanel.panelItems.form.control] ==> parent_form',
              id: 'parent_view[layoutpanel.panelitems.form.control] ==> parent_form',
            },
          ],
          topPos: 208,
          name: '准备参数',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'grid',
          ctrlParam: true,
          name: '表格',
          id: 'grid',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图',
          id: 'view',
        },
        {
          codeName: 'parent_form',
          entityParam: true,
          name: '父表单',
          id: 'parent_form',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '上下文',
          id: 'ctx',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'parent_view',
          entityParam: true,
          name: '父视图',
          id: 'parent_view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '开始当前阶段评审',
      id: 'start_cur_stage_review',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '建立',
      mapDEName: 'REVIEW',
      mapDEOPPrivName: 'CREATE',
      name: 'CREATE',
      id: 'review__create',
    },
    {
      logicName: '删除',
      mapDEName: 'REVIEW',
      mapDEOPPrivName: 'DELETE',
      name: 'DELETE',
      id: 'review__delete',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '读取',
      mapDEName: 'REVIEW',
      mapDEOPPrivName: 'READ',
      name: 'READ',
      id: 'review__read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
    {
      logicName: '修改',
      mapDEName: 'REVIEW',
      mapDEOPPrivName: 'UPDATE',
      name: 'UPDATE',
      id: 'review__update',
    },
  ],
  codeName: 'review_content',
  deapicodeName: 'review_content',
  deapicodeName2: 'review_contents',
  deapitag: 'REVIEW_CONTENT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.REVIEW_CONTENT',
  },
  logicName: '评审内容',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'review_contents',
      majorAppDataEntityId: 'plmweb.review',
      parentAppDEFieldId: 'principal_id',
      rsmode: 2,
      name: 'DERCUSTOM_REVIEW_CONTENT_REVIEW',
      id: 'review_contents',
    },
    {
      actionRSMode: 1,
      codeName: 'review_contents',
      majorAppDataEntityId: 'plmweb.review_wizard',
      parentAppDEFieldId: 'principal_id',
      rsmode: 2,
      name: 'DERCUSTOM_REVIEW_CONTENT_REVIEW_WIZARD',
      id: 'review_contents',
    },
    {
      actionRSMode: 1,
      codeName: 'review_contents',
      majorAppDataEntityId: 'plmweb.test_case',
      parentAppDEFieldId: 'target_id',
      rsmode: 2,
      name: '用例-评审内容',
      id: 'review_contents',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['principal_id', 'target_id'],
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'REVIEW_CONTENT',
  id: 'plmweb.review_content',
  codeName2: 'review_contents',
  requestPaths: [
    'libraries/${library}/reviews/${review}/review_contents/${review_content}',
    'products/${product}/reviews/${review}/review_contents/${review_content}',
    'libraries/${library}/review_wizards/${review_wizard}/review_contents/${review_content}',
    'libraries/${library}/test_cases/${test_case}/review_contents/${review_content}',
    'reviews/${review}/review_contents/${review_content}',
    'review_wizards/${review_wizard}/review_contents/${review_content}',
    'test_cases/${test_case}/review_contents/${review_content}',
  ],
};
