export default {
  appDEFields: [
    {
      codeName: 'principal_id',
      logicName: '关联主体标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_ID',
      id: 'principal_id',
    },
    {
      codeName: 'change_type',
      logicName: '变更类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CHANGE_TYPE',
      id: 'change_type',
    },
    {
      codeName: 'owner_type',
      logicName: '所属数据对象',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_TYPE',
      id: 'owner_type',
    },
    {
      codeName: 'principal_type',
      logicName: '关联主体类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      codeName: 'change_version',
      logicName: '变更版本',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CHANGE_VERSION',
      id: 'change_version',
    },
    {
      codeName: 'stage_results',
      logicName: '评审结果',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'STAGE_RESULTS',
      id: 'stage_results',
    },
    {
      codeName: 'target_type',
      logicName: '关联目标类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TYPE',
      id: 'target_type',
    },
    {
      codeName: 'final_stage_results',
      logicName: '最终评审结果',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FINAL_STAGE_RESULTS',
      id: 'final_stage_results',
    },
    {
      codeName: 'parent_version_id',
      logicName: '父对象版本标识',
      predefinedType: 'PARENTVERSIONID',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_VERSION_ID',
      id: 'parent_version_id',
    },
    {
      codeName: 'target_version_id',
      logicName: '目标对象版本标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_VERSION_ID',
      id: 'target_version_id',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_time',
      logicName: '创建时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_time',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'create_man',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'update_man',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'review_data',
      logicName: '评审数据',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'REVIEW_DATA',
      id: 'review_data',
    },
    {
      codeName: 'idea',
      logicName: '产品需求',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'IDEA',
      id: 'idea',
    },
    {
      codeName: 'cur_version_id',
      logicName: '当前版本标识',
      predefinedType: 'VERSIONID',
      stdDataType: 25,
      stringLength: 100,
      name: 'CUR_VERSION_ID',
      id: 'cur_version_id',
    },
    {
      codeName: 'target_identifier',
      logicName: '目标对象编号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_IDENTIFIER',
      id: 'target_identifier',
    },
    {
      codeName: 'target_title',
      logicName: '目标对象标题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_TITLE',
      id: 'target_title',
    },
    {
      codeName: 'target_state',
      logicName: '目标对象状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_STATE',
      id: 'target_state',
    },
    {
      codeName: 'target_assignee',
      logicName: '目标对象负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ASSIGNEE',
      id: 'target_assignee',
    },
    {
      codeName: 'target_version',
      logicName: '关联目标版本',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TARGET_VERSION',
      id: 'target_version',
    },
    {
      codeName: 'target_priority',
      logicName: '目标对象优先级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PRIORITY',
      id: 'target_priority',
    },
    {
      codeName: 'target_parent_id',
      logicName: '目标对象父标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_PARENT_ID',
      id: 'target_parent_id',
    },
    {
      codeName: 'target_id',
      logicName: '关联目标标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TARGET_ID',
      id: 'target_id',
    },
  ],
  appDELogics: [
    {
      codeName: 'nothing',
      defaultParamName: 'Default',
      logicName: '无操作',
      logicSubType: 'NONE',
      delogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
      ],
      delogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          paramAppDataEntityId: 'plmweb.review_content_idea',
          name: '传入变量',
          id: 'default',
        },
      ],
      startDELogicNodeId: 'begin',
      enableFront: true,
      valid: true,
      name: '无操作',
      id: 'nothing',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'review_content_idea_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'change_type',
          logicName: '变更类型',
          appDEFieldId: 'change_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'change_type',
        },
        {
          codeName: 'principal_id',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_id',
        },
        {
          codeName: 'change_version',
          logicName: '变更版本',
          appDEFieldId: 'change_version',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          listMap: true,
          id: 'change_version',
        },
        {
          codeName: 'owner_type',
          logicName: '所属数据对象',
          appDEFieldId: 'owner_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_type',
        },
        {
          codeName: 'principal_type',
          logicName: '关联主体类型',
          appDEFieldId: 'principal_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'principal_type',
        },
        {
          codeName: 'stage_results',
          logicName: '评审结果',
          appDEFieldId: 'stage_results',
          refAppDEMethodDTOId: 'review_result_dto',
          refAppDataEntityId: 'plmweb.review_result',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'stage_results',
        },
        {
          codeName: 'final_stage_results',
          logicName: '最终评审结果',
          appDEFieldId: 'final_stage_results',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'final_stage_results',
        },
        {
          codeName: 'target_type',
          logicName: '关联目标类型',
          appDEFieldId: 'target_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_type',
        },
        {
          codeName: 'parent_version_id',
          logicName: '父对象版本标识',
          appDEFieldId: 'parent_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_version_id',
        },
        {
          codeName: 'target_version_id',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_version_id',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '创建时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
        {
          codeName: 'create_man',
          logicName: '建立人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'review_data',
          logicName: '评审数据',
          appDEFieldId: 'review_data',
          refAppDEMethodDTOId: 'review_dto',
          refAppDataEntityId: 'plmweb.review',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'review_data',
        },
        {
          codeName: 'idea',
          logicName: '产品需求',
          appDEFieldId: 'idea',
          refAppDEMethodDTOId: 'idea_dto',
          refAppDataEntityId: 'plmweb.idea',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'idea',
        },
        {
          codeName: 'cur_version_id',
          logicName: '当前版本标识',
          appDEFieldId: 'cur_version_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cur_version_id',
        },
        {
          codeName: 'target_identifier',
          logicName: '目标对象编号',
          appDEFieldId: 'target_identifier',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_identifier',
        },
        {
          codeName: 'target_title',
          logicName: '目标对象标题',
          appDEFieldId: 'target_title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_title',
        },
        {
          codeName: 'target_state',
          logicName: '目标对象状态',
          appDEFieldId: 'target_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_state',
        },
        {
          codeName: 'target_assignee',
          logicName: '目标对象负责人',
          appDEFieldId: 'target_assignee',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_assignee',
        },
        {
          codeName: 'target_version',
          logicName: '关联目标版本',
          appDEFieldId: 'target_version',
          refAppDEMethodDTOId: 'version_dto',
          refAppDataEntityId: 'plmweb.version',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'target_version',
        },
        {
          codeName: 'target_priority',
          logicName: '目标对象优先级',
          appDEFieldId: 'target_priority',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_priority',
        },
        {
          codeName: 'target_parent_id',
          logicName: '目标对象父标识',
          appDEFieldId: 'target_parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_parent_id',
        },
        {
          codeName: 'target_id',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'target_id',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'review_content_idea_dto',
    },
    {
      codeName: 'review_content_idea_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_principal_id_eq',
          logicName: '关联主体标识',
          appDEFieldId: 'principal_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_principal_id_eq',
        },
        {
          codeName: 'n_target_id_eq',
          logicName: '关联目标标识',
          appDEFieldId: 'target_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_id_eq',
        },
        {
          codeName: 'n_target_version_id_eq',
          logicName: '目标对象版本标识',
          appDEFieldId: 'target_version_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_target_version_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'review_content_idea_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'nothing',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        name: 'NothingInput',
        id: 'nothinginput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'NothingResult',
        id: 'nothingresult',
      },
      actionMode: 'CUSTOM',
      actionType: 'DELOGIC',
      appDELogicId: 'nothing',
      dataSetType: 'REMOTE',
      id: 'nothing',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'review_content_total',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/review_content_total',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'review_content_total',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      sysPFPluginId: 'review_content_sort',
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_cur_history',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_history',
      actionType: 'REMOTE',
      dataSetName: 'cur_history',
      dataSetTag: 'cur_history',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_history',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_history_list',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'review_content_idea_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'review_content_idea_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_history_list',
      actionType: 'REMOTE',
      dataSetName: 'history_list',
      dataSetTag: 'history_list',
      dataSetType: 'REMOTE',
      id: 'fetch_history_list',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '移出需求',
      codeName: 'remove_idea_all',
      confirmMsg: '确定移除该需求？',
      fullCodeName: 'REVIEW_CONTENT_IDEA_remove_idea_all',
      appDEMethodId: 'remove',
      sysImage: {
        cssClass: 'fa fa-mail-reply',
        glyph: 'xf112@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '移除成功',
      timeout: 60000,
      tooltip: '移出',
      uiactionMode: 'BACKEND',
      uiactionTag: 'remove_idea_all',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'plmweb.review_content_idea',
      name: '移出需求（无权限）',
      id: 'remove_idea_all@review_content_idea',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'REVIEW_CONTENT_IDEA',
  deapicodeName: 'review_content_idea',
  deapicodeName2: 'review_content_ideas',
  deapitag: 'REVIEW_CONTENT_IDEA',
  decodeName: 'review_content_idea',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 2,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.REVIEW_CONTENT_IDEA',
  },
  logicName: '产品需求评审内容',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'review_content_ideas',
      majorAppDataEntityId: 'plmweb.review',
      parentAppDEFieldId: 'principal_id',
      rsmode: 2,
      name: 'DERCUSTOM_REVIEW_CONTENT_IDEA_REVIEW',
      id: 'review_content_ideas',
    },
    {
      actionRSMode: 1,
      codeName: 'review_content_ideas',
      majorAppDataEntityId: 'plmweb.review_wizard',
      parentAppDEFieldId: 'principal_id',
      rsmode: 2,
      name: 'DERCUSTOM_REVIEW_CONTENT_IDEA_REVIEW_WIZARD',
      id: 'review_content_ideas',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['principal_id', 'target_id'],
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'REVIEW_CONTENT_IDEA',
  id: 'plmweb.review_content_idea',
  codeName2: 'REVIEW_CONTENT_IDEAS',
  requestPaths: [
    'reviews/${review}/review_content_ideas/${review_content_idea}',
    'review_wizards/${review_wizard}/review_content_ideas/${review_content_idea}',
  ],
};
