export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProdMgmt__solutions',
  codeListType: 'DYNAMIC',
  codeName: 'ProdMgmt__solutions',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_ticket_solution',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '进入需求池',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '技术排期',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '待进一步确认',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_40',
      text: '方案调研',
      value: '40',
      id: 'item_40',
    },
    {
      codeName: 'item_50',
      text: '暂时搁置',
      value: '50',
      id: 'item_50',
    },
    {
      codeName: 'item_60',
      text: '功能已支持',
      value: '60',
      id: 'item_60',
    },
    {
      codeName: 'item_70',
      text: '不予采纳',
      value: '70',
      id: 'item_70',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  name: '工单解决方案',
  id: 'plmweb.prodmgmt__solutions',
};
