export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__work_item_priority',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__work_item_priority',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_work_item_priority',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_40',
      color: '#FF1900',
      sysCss: {
        cssName: 'red-span',
      },
      text: '紧急',
      textCls: 'red-span',
      value: '40',
      id: 'item_40',
    },
    {
      codeName: 'item_30',
      color: '#D58A3A',
      sysCss: {
        cssName: 'orange-span',
      },
      text: '高',
      textCls: 'orange-span',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_20',
      color: '#002FFF',
      sysCss: {
        cssName: 'blue-span',
      },
      text: '中',
      textCls: 'blue-span',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_10',
      color: '#10691B',
      sysCss: {
        cssName: 'green-span',
      },
      text: '低',
      textCls: 'green-span',
      value: '10',
      id: 'item_10',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  name: '优先级',
  id: 'plmweb.projmgmt__work_item_priority',
};
