export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__severity',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__severity',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_work_item_severity',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '致命',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '严重',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '一般',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_40',
      text: '建议',
      value: '40',
      id: 'item_40',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  userParam: {
    globalCache: 'true',
  },
  name: '严重程度',
  id: 'plmweb.projmgmt__severity',
};
