export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__reproduction_probability',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__reproduction_probability',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_work_item_probability',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '必现',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '大概率复现',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '小概率复现',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_40',
      text: '仅出现一次',
      value: '40',
      id: 'item_40',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  userParam: {
    globalCache: 'true',
  },
  name: '复现概率',
  id: 'plmweb.projmgmt__reproduction_probability',
};
