export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__demand_sources',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__demand_sources',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_idea_source',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '产品规划',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '用户反馈',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '内部需求',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_40',
      text: '竞品调研',
      value: '40',
      id: 'item_40',
    },
    {
      codeName: 'item_50',
      text: '其他',
      value: '50',
      id: 'item_50',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  name: '需求来源',
  id: 'plmweb.projmgmt__demand_sources',
};
