export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__risk',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__risk',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_work_item_risk',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '高',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '中',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '低',
      value: '30',
      id: 'item_30',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  name: '风险',
  id: 'plmweb.projmgmt__risk',
};
