export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'ProjMgmt__requirement_type',
  codeListType: 'DYNAMIC',
  codeName: 'ProjMgmt__requirement_type',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_idea_type',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'item_10',
      text: '技术需求',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_20',
      text: '功能需求',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_30',
      text: '安全需求',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_40',
      text: '体验优化',
      value: '40',
      id: 'item_40',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  userParam: {
    globalCache: 'true',
  },
  name: '需求类型',
  id: 'plmweb.projmgmt__requirement_type',
};
