export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'TestMgmt__test_case_test_type',
  codeListType: 'DYNAMIC',
  codeName: 'TestMgmt__test_case_test_type',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_test_case_test_type',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'automation',
      text: '自动',
      value: 'automation',
      id: 'automation',
    },
    {
      codeName: 'manual',
      text: '手动',
      value: 'manual',
      id: 'manual',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  name: '测试类型',
  id: 'plmweb.testmgmt__test_case_test_type',
};
