export default {
  cacheTimeout: 1000,
  clsAppDEFieldId: 'style',
  codeListTag: 'TestMgmt__test_case_level',
  codeListType: 'DYNAMIC',
  codeName: 'TestMgmt__test_case_level',
  colorAppDEFieldId: 'color',
  emptyText: '未定义',
  minorSortDir: 'ASC',
  minorSortAppDEFieldId: 'sequence',
  appDEDataSetId: 'fetch_test_case_importance_level',
  appDataEntityId: 'plmweb.dictionary_data',
  codeItems: [
    {
      codeName: 'p0',
      text: 'P0',
      value: 'P0',
      id: 'p0',
    },
    {
      codeName: 'p1',
      text: 'P1',
      value: 'P1',
      id: 'p1',
    },
    {
      codeName: 'p2',
      text: 'P2',
      value: 'P2',
      id: 'p2',
    },
    {
      codeName: 'p3',
      text: 'P3',
      value: 'P3',
      id: 'p3',
    },
    {
      codeName: 'p4',
      text: 'P4',
      value: 'P4',
      id: 'p4',
    },
  ],
  textAppDEFieldId: 'name',
  valueAppDEFieldId: 'val',
  enableCache: true,
  userParam: {
    globalCache: 'true',
  },
  name: '用例重要程度',
  id: 'plmweb.testmgmt__test_case_level',
};
