export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'review_re_page_view',
  deviewId: '8011AD5C-B184-4C44-9BBF-B45D9F5118C6',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '选择页面',
  codeName: 'article_page_review_re_page_view',
  appDataEntityId: 'plmweb.article_page',
  appViewNavParams: [
    {
      key: 'space',
      value: 'space',
      id: 'space',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId:
        'plmweb.article_page_not_add_pick_up_grid_view_review',
      codeName: 'review_re_page_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'review_re_page_view_pickupviewpanel',
    },
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 空间名称',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'node',
              parentValueLevel: 1,
              searchMode: 3,
              id: '空间名称 - 全部',
            },
          ],
          detreeNodes: [
            {
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              dataSourceType: 'DEDATASET',
              idAppDEFieldId: 'id',
              appDEDataSetId: 'fetch_current',
              textAppDEFieldId: 'name',
              nodeType: 'node',
              appDataEntityId: 'plmweb.space',
              treeNodeType: 'DE',
              hasDETreeNodeRSs: true,
              disableSelect: true,
              expanded: true,
              name: '空间名称',
              id: 'node',
            },
            {
              text: '全部',
              nodeType: 'node_1',
              treeNodeType: 'STATIC',
              disableSelect: true,
              selected: true,
              name: '全部',
              id: 'node_1',
            },
          ],
          outputIconDefault: true,
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'plmweb.article_page',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'plmweb.article_page',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'plmweb.article_page',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'plmweb.article_page',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'plmweb.article_page',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'page_mpick_up_tree',
          controlType: 'TREEVIEW',
          logicName: '页面评审多项选择树',
          appDataEntityId: 'plmweb.article_page',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          modelId: '4b399200b4c40f6dd7b1cd4761179c24',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'plmweb.article_page.page_mpick_up_tree',
        },
      ],
      codeName: 'review_re_page_view_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '9767caf28ba99dcec81d4b48c866a5dd_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'review_re_page_view_treeexpbar',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                editor: {
                  halign: 'LEFT',
                  renderMode: 'TEXT_DYNAMIC',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'name',
                },
                viewFieldName: 'NAME',
                allowEmpty: true,
                caption: '文本(动态)',
                itemStyle: 'DEFAULT',
                itemType: 'FIELD',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'name',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0804340234',
        controlType: 'PANEL',
        logicName: 'simplelist_列表项面板',
        appDataEntityId: 'plmweb.article_page',
        controlParam: {},
        modelId: '3123DE30-F6C3-4EBB-92E6-C3E86908F061',
        modelType: 'PSSYSVIEWPANEL',
        name: 'simplelist_itempanel',
        id: 'plmweb.article_page.usr0804340234',
      },
      orderValueAppDEFieldId: 'sequence',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'id',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'space_id',
          dataType: 25,
          id: 'space_id',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'parent_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.article_page',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.article_page',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.article_page',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.article_page',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.article_page',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '8E60B740-2DE4-4130-80BF-C53DBC9B5A23',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'plmweb.article_page.simplelist',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAGE',
      },
      caption: '选择页面',
      codeName: 'review_re_page_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {},
      name: 'captionbar',
      id: 'review_re_page_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW2',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '选择页面',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW2',
  enableDP: true,
  showCaptionBar: false,
  modelId: '9767caf28ba99dcec81d4b48c866a5dd',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pagereview_re_page_view',
  id: 'plmweb.article_page_review_re_page_view',
};
