export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'not_add_pick_up_grid_view_review',
  deviewId: 'B565AC24-31C8-438C-B88B-05BCD77A51CF',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '页面',
  codeName: 'article_page_not_add_pick_up_grid_view_review',
  appDataEntityId: 'plmweb.article_page',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IDEA.IDENTIFIER',
          },
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '页面名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.NAME',
          },
          caption: '页面名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'choose_version_name',
          excelCaption: '版本',
          appDEFieldId: 'choose_version_name',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '版本',
          codeName: 'choose_version_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          sysPFPluginId: 'jscode_grid_column',
          width: 100,
          widthUnit: 'PX',
          id: 'choose_version_name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'type',
          excelCaption: '类型',
          appCodeListId: 'plmweb.wiki__page_type',
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '类型',
          codeName: 'type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 100,
          widthUnit: 'PX',
          enableSort: true,
          id: 'type',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'choose_version_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'choose_version_name',
        },
        {
          appDEFieldId: 'type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'type',
        },
        {
          appDEFieldId: 'choose_version_id',
          scriptCode: 'data.cur_version_id',
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 25,
          id: 'choose_version_id',
        },
        {
          appDEFieldId: 'cur_version_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'cur_version_name',
        },
        {
          appDEFieldId: 'cur_version_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'cur_version_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'space_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'space_id',
        },
        {
          appDEFieldId: 'parent_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'parent_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '版本',
          codeName: 'choose_version_name',
          enableCond: 3,
          appDEFieldId: 'choose_version_name',
          editor: {
            enablePickupView: true,
            singleSelect: true,
            appDEACModeId: 'default',
            appDEDataSetId: 'fetch_default',
            appDataEntityId: 'plmweb.version',
            enableAC: true,
            forceSelection: true,
            showTrigger: true,
            valueItemName: 'choose_version_id',
            editorParams: {
              INITSCRIPTCODE:
                'data.choose_version_id = data.cur_version_id;data.choose_version_name = data.cur_version_name',
              'SRFNAVPARAM.n_owner_id_eq': '%id%',
              AC: 'TRUE',
              PICKUPVIEW: 'TRUE',
              ENABLESAVE: 'false',
            },
            editorType: 'PICKER',
            editorItems: [{}],
            valueType: 'SIMPLE',
            editable: true,
            navigateParams: [
              {
                key: 'n_owner_id_eq',
                value: 'id',
                id: 'n_owner_id_eq',
              },
            ],
            id: 'choose_version_name',
          },
          allowEmpty: true,
          id: 'choose_version_name',
        },
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
        {
          enableCond: 3,
          appDEFieldId: 'choose_version_id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
          },
          allowEmpty: true,
          id: 'choose_version_id',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'plmweb.article_page',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.article_page',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'review_mpick_up_grid',
      controlType: 'GRID',
      logicName: '评审页面多项选择表格',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'grid',
      },
      modelId: '6dc57e452f0500d8962c988b5aec5e4d',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.article_page.review_mpick_up_grid',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAGE',
      },
      caption: '页面',
      codeName: 'not_add_pick_up_grid_view_review_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {},
      name: 'captionbar',
      id: 'not_add_pick_up_grid_view_review_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '未添加的页面表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '41bc1f589679ca7e1d3868d55e3de45d',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pagenot_add_pick_up_grid_view_review',
  id: 'plmweb.article_page_not_add_pick_up_grid_view_review',
};
