export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'version_comparison_view',
  deviewId: 'F229CC35-F214-4399-B56B-865E318AB687',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PAGE',
  },
  caption: '版本对比',
  codeName: 'article_page_version_comparison_view',
  appDataEntityId: 'plmweb.article_page',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.article_page',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.article_page',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.article_page',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.article_page',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.article_page',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.article_page',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'name',
              editor: {
                maxLength: 200,
                editorType: 'TEXTBOX',
                valueType: 'SIMPLE',
                editable: true,
                id: 'title',
              },
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.NAME',
              },
              caption: '主题',
              codeName: 'title',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'title',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'type',
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.wiki__page_type',
                editorType: 'DROPDOWNLIST',
                valueType: 'SIMPLE',
                editable: true,
                id: 'type',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '类型',
              codeName: 'type',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'type',
            },
            {
              dataType: 25,
              enableCond: 3,
              ignoreInput: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'publish_man',
              editor: {
                halign: 'LEFT',
                valign: 'MIDDLE',
                wrapMode: 'NOWRAP',
                appCodeListId: 'plmweb.sysoperator',
                editorStyle: 'PERSONNEL_INFO',
                editorType: 'SPAN',
                sysPFPluginId: 'personnel_info',
                valueType: 'SIMPLE',
                editable: true,
                id: 'publish_man',
              },
              allowEmpty: true,
              convertToCodeItemText: true,
              caption: '发布人',
              codeName: 'publish_man',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'publish_man',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 21,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'publish_content',
                  editor: {
                    contentType: 'HTML',
                    editorParams: {
                      contenttype: 'HTML',
                      PARSESCRIPT:
                        'value?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\\\'comment-tag\\\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g,(x, value, icon) => { const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                    },
                    editorStyle: 'ANCHO_HTML',
                    editorType: 'RAW',
                    sysPFPluginId: 'ancho_html',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'publish_content',
                  },
                  allowEmpty: true,
                  caption: '发布正文',
                  codeName: 'publish_content',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'publish_content',
                },
              ],
              caption: '页面内容',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  contentType: 'REPEATER',
                  appDEFieldId: 'attachments',
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'name',
                      },
                      allowEmpty: true,
                      codeName: 'name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'name',
                    },
                  ],
                  codeName: 'mdctrl1',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'mdctrl1',
                },
              ],
              caption: '附件',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'comparison_form',
      controlStyle: 'FORM_DATA_COMPARISON',
      controlType: 'FORM',
      logicName: '版本对比表单',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        ctrlParams: {
          RESPONSEMAP: '{"id":"id","label":"name"}',
          REQUESTURL: '/versions/fetch_default',
          REQUESTPARAMS: '`${context.article_page}`',
          REQUESTMETHOD: 'post',
        },
        id: 'form',
      },
      sysPFPluginId: 'form_data_comparison',
      modelId: '4796A1C1-CC0A-47A1-9AC4-F9E6B6F0F136',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.article_page.comparison_form',
    },
    {
      codeName: 'version_comparison_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'version_comparison_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PAGE',
      },
      caption: '版本对比',
      codeName: 'version_comparison_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.article_page',
      controlParam: {},
      name: 'captionbar',
      id: 'version_comparison_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.article_page',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '页面版本对比',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'fdfb564692544e2bd534eeb7a13f98bb',
  modelType: 'PSAPPDEVIEW',
  name: 'article_pageversion_comparison_view',
  id: 'plmweb.article_page_version_comparison_view',
};
