export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'list_view',
  deviewId: '2cd57b81d6d3e24a97d721002d13a493',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.COMMENT',
  },
  caption: '评论',
  codeName: 'comment_list_view',
  appDataEntityId: 'plmweb.comment',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'ARTICLE_PAGE',
      name: 'ARTICLE_PAGE',
      id: 'article_page',
    },
    {
      rawValue: true,
      key: 'SPACE',
      name: 'SPACE',
      id: 'space',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_type_eq',
      value: 'principal_type',
      id: 'n_owner_type_eq',
    },
    {
      key: 'n_principal_id_eq',
      value: 'principal_id',
      id: 'n_principal_id_eq',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '列表',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'list',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'ListView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'plmweb.comment_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.comment_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'plmweb.comment_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'plmweb.comment_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '评论编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.COMMENT.EDITVIEW',
        },
        refAppViewId: 'plmweb.comment_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '评论编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.COMMENT.EDITVIEW',
        },
        refAppViewId: 'plmweb.comment_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'plmweb.sysoperator',
                            editorStyle: 'PERSONNEL_INFO',
                            editorType: 'SPAN',
                            sysPFPluginId: 'personnel_info',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'user_name',
                          },
                          viewFieldName: 'CREATE_MAN',
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'user_name',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'time',
                          },
                          viewFieldName: 'CREATE_TIME',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          cssStyle:
                            'line-height: var(--ibiz-height-control-default);',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingLeft: 'OUTERMEDIUM',
                          },
                          sysCss: {
                            cssName: 'transition-time',
                          },
                          id: 'time',
                        },
                        {
                          rawItem: {
                            caption: '置顶',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            id: 'top_text',
                          },
                          caption: '置顶',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingLeft: 'OUTERSMALL',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['is_top'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'EQ',
                                  dstModelField: 'IS_TOP',
                                  value: '1',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                            },
                          ],
                          showCaption: true,
                          id: 'top_text',
                        },
                        {
                          editor: {
                            editorType: 'HIDDEN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'field_text_dynamic3',
                          },
                          viewFieldName: 'ID',
                          allowEmpty: true,
                          hidden: true,
                          caption: '文本(动态)',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'field_text_dynamic3',
                        },
                        {
                          editor: {
                            editorType: 'HIDDEN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'pid',
                          },
                          viewFieldName: 'PID',
                          allowEmpty: true,
                          hidden: true,
                          caption: '文本(动态)',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'pid',
                        },
                        {
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'is_top',
                          },
                          viewFieldName: 'IS_TOP',
                          allowEmpty: true,
                          hidden: true,
                          caption: '文本(动态)',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'is_top',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      sysCss: {
                        cssName: 'top_style',
                      },
                      id: 'container1',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEMS',
                          buttonListType: 'UIACTIONGROUP',
                          uiactionGroup: {
                            uiactionGroupDetails: [
                              {
                                actionLevel: 100,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                buttonStyle: 'DEFAULT',
                                caption: '置顶',
                                detailType: 'DEUIACTION',
                                uiactionId: 'top@comment',
                                visibleScriptCode: 'data.is_top!=1',
                                showCaption: true,
                                showIcon: true,
                                sysImage: {
                                  rawContent:
                                    '<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1747741120326" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="4339" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16"><path d="M576 452.266667v422.4h-85.333333v-422.4l-89.6 89.6L341.333333 477.866667l192-192 192 192-59.733333 59.733333-89.6-85.333333z m213.333333-217.6h-512v-85.333334h512v85.333334z" fill="#444444" p-id="4340"></path></svg>',
                                },
                                id: 'u97e6419',
                              },
                              {
                                actionLevel: 100,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                buttonStyle: 'DEFAULT',
                                caption: '取消置顶',
                                detailType: 'DEUIACTION',
                                uiactionId: 'no_top@comment',
                                visibleScriptCode: 'data.is_top==1',
                                showCaption: true,
                                showIcon: true,
                                sysImage: {
                                  rawContent:
                                    '<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1747741189924" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="8698" xmlns:xlink="http://www.w3.org/1999/xlink" width="16" height="16"><path d="M228.43 433.23l70.893 63.016-47.261 39.385-78.77-63.016 55.139-39.384z m141.785-118.153L512 196.923l330.83 267.815-78.768 63.016-196.924-165.416v141.785L456.862 393.846v-23.63l-15.754 7.876-70.893-63.015z m196.923 441.108V1024H456.862V653.785l110.276 102.4zM39.385 86.646V0h945.23v86.646H39.385zM102.4 252.062l63.015-70.893 748.308 716.8-63.015 70.893-748.308-716.8z" p-id="8699"></path></svg>',
                                },
                                id: 'uaa719ea',
                              },
                              {
                                actionLevel: 100,
                                afterItemType: 'NONE',
                                beforeItemType: 'NONE',
                                buttonStyle: 'DEFAULT',
                                caption: '删除',
                                detailType: 'DEUIACTION',
                                uiactionId: 'del_comment@comment',
                                visibleScriptCode:
                                  'data.create_man === context.srfuserid',
                                showCaption: true,
                                showIcon: true,
                                sysImage: {
                                  cssClass: 'fa fa-trash-o',
                                  glyph: 'xf014@FontAwesome',
                                },
                                id: 'ue61f196',
                              },
                            ],
                            appDataEntityId: 'plmweb.comment',
                            uniqueTag: 'comment__Usr0519465800',
                            name: '评论列表行为组',
                            id: 'usr0519465800',
                          },
                          itemStyle: 'STYLE2',
                          itemType: 'BUTTONLIST',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysCss: {
                            cssName: 'comment_btn_style',
                          },
                          sysImage: {
                            cssClass: 'fa fa-ellipsis-v',
                            glyph: 'xf142@FontAwesome',
                          },
                          id: 'top',
                        },
                        {
                          actionType: 'UIACTION',
                          buttonStyle: 'STYLE2',
                          buttonType: 'PANELBUTTON',
                          uiactionId:
                            'panel_usr0103471499_button_calluilogic1_click@comment',
                          renderMode: 'BUTTON',
                          tooltip: '编辑',
                          uiactionTarget: 'SINGLEDATA',
                          caption: '编辑',
                          itemStyle: 'STYLE2',
                          itemType: 'BUTTON',
                          controlLogics: [
                            {
                              itemName: 'BUTTON_CALLUILOGIC1',
                              logicTag: 'list_itempanel',
                              logicType: 'SCRIPT',
                              scriptCode:
                                'data.create_man === context.srfuserid',
                              triggerType: 'ITEMVISIBLE',
                              id: 'logic',
                            },
                          ],
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysImage: {
                            cssClass: 'fa fa-edit',
                            glyph: 'xf044@FontAwesome',
                          },
                          id: 'button_calluilogic1',
                        },
                        {
                          actionType: 'UIACTION',
                          buttonStyle: 'STYLE2',
                          buttonType: 'PANELBUTTON',
                          uiactionId:
                            'panel_usr0103471499_button_calluilogic2_click@comment',
                          renderMode: 'BUTTON',
                          tooltip: '回复',
                          uiactionTarget: 'SINGLEDATA',
                          caption: '回复',
                          itemStyle: 'STYLE2',
                          itemType: 'BUTTON',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysImage: {
                            cssClass: 'fa fa-comment-o',
                            glyph: 'xf0e5@FontAwesome',
                          },
                          id: 'button_calluilogic2',
                        },
                      ],
                      layout: {
                        dir: 'row-reverse',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      controlLogics: [
                        {
                          itemName: 'CONTAINER2',
                          logicTag: 'list_itempanel',
                          logicType: 'SCRIPT',
                          scriptCode: 'context.srfreadonly != true',
                          triggerType: 'ITEMVISIBLE',
                          name: 'readOnly',
                          id: 'readonly',
                        },
                      ],
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      panelItemGroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedItemNames: ['field_text_dynamic2'],
                          groupOP: 'AND',
                          panelItemLogics: [
                            {
                              condOp: 'NOTEQ',
                              dstModelField: 'FIELD_TEXT_DYNAMIC2',
                              value: '<p><del>该评论已删除</del></p>',
                              logicType: 'SINGLE',
                              id: '逻辑项',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      id: 'container2',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        contentType: 'HTML',
                        editorParams: {
                          contenttype: 'HTML',
                          LINKVIEWID: 'plmweb.recent_custom_redirect_view',
                          SCRIPTCODE:
                            'data.content?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\'comment-tag\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\'comment-tag\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g, (x, value, icon) => {const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                          TRANSLATEOBJ: '{"&reg":"&amp;reg"}',
                        },
                        editorStyle: 'COMMENT_ITEM',
                        editorType: 'RAW',
                        sysPFPluginId: 'comment_item',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'field_text_dynamic2',
                      },
                      viewFieldName: 'CONTENT',
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'field_text_dynamic2',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'plmweb.sysoperator',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'pcreate_man',
                          },
                          viewFieldName: 'PCREATE_MAN',
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 0,
                            layout: 'FLEX',
                          },
                          id: 'pcreate_man',
                        },
                        {
                          rawItem: {
                            caption: '：',
                            halign: 'LEFT',
                            renderMode: 'PARAGRAPH',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_LABEL',
                            id: 'static_label',
                          },
                          caption: '标签',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 0,
                            layout: 'FLEX',
                          },
                          showCaption: true,
                          id: 'static_label',
                        },
                        {
                          editor: {
                            contentType: 'HTML',
                            editorParams: {
                              contenttype: 'HTML',
                              SCRIPTCODE:
                                'data.content?.replace(/@{[^,]*,"name":"(.*?)"}/g,"<span class=\'comment-tag\'>@$1</span>").replace(/@{[^,]*,name=(.*?)}/g,"<span class=\'comment-tag\'>@$1</span>").replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g, (x, value, icon) => {const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1).trim(); } return controller.parseCommentTag({icon, ...item});}).replaceAll(/\\{\\"\\emoji\\":\\"(.+?)\\"\\}/g,(x, emoji) => {const tempVal = decodeURIComponent(atob(emoji)); return `<span class="emoji-tag">${tempVal}</span>`})',
                              TRANSLATEOBJ: '{"&reg":"&amp;reg"}',
                            },
                            editorStyle: 'COMMENT_ITEM',
                            editorType: 'RAW',
                            sysPFPluginId: 'comment_item',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'pcontent',
                          },
                          viewFieldName: 'PCONTENT',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            grow: 1,
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'pcontent',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      panelItemGroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedItemNames: ['pid'],
                          groupOP: 'AND',
                          panelItemLogics: [
                            {
                              condOp: 'ISNOTNULL',
                              dstModelField: 'PID',
                              logicType: 'SINGLE',
                              id: '逻辑项',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      sysCss: {
                        cssName: 'comment-replay',
                      },
                      id: 'container3',
                    },
                  ],
                  layout: {
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  cssStyle: 'padding-left: 36px;',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container4',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'usr0103471499',
          controlType: 'PANEL',
          logicName: 'list_列表项面板',
          appDataEntityId: 'plmweb.comment',
          controlParam: {},
          modelId: 'ee886f58af63fee0ca6e9603df7aaa8e',
          modelType: 'PSSYSVIEWPANEL',
          name: 'list_itempanel',
          id: 'plmweb.comment.usr0103471499',
        },
        delistDataItems: [
          {
            appDEFieldId: 'create_time',
            dataType: 5,
            format: 'YYYY-MM-DD HH:mm:ss',
            id: 'create_time',
          },
          {
            appDEFieldId: 'content',
            dataType: 21,
            id: 'content',
          },
          {
            appDEFieldId: 'create_man',
            frontCodeListId: 'plmweb.sysoperator',
            dataType: 25,
            id: 'create_man',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'pcreate_man',
            frontCodeListId: 'plmweb.sysoperator',
            dataType: 25,
            id: 'pcreate_man',
          },
          {
            appDEFieldId: 'pid',
            dataType: 25,
            id: 'pid',
          },
          {
            appDEFieldId: 'pcontent',
            dataType: 21,
            id: 'pcontent',
          },
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingSize: 1000,
        noSort: true,
        showHeader: true,
        singleSelect: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'plmweb.comment',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'plmweb.comment',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'plmweb.comment',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'plmweb.comment',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'plmweb.comment',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'list',
        controlType: 'LIST',
        logicName: 'list',
        appDataEntityId: 'plmweb.comment',
        controlParam: {
          id: 'list',
        },
        sysCss: {
          cssName: 'comment-list-height-auto',
        },
        modelId: '9b4452e60e1fe2c3e394cd0199c78969',
        modelType: 'PSDELIST',
        name: 'list',
        id: 'plmweb.comment.list',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'plmweb.comment',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.COMMENT',
        },
        caption: '评论',
        codeName: 'list_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.comment',
        controlParam: {},
        name: 'captionbar',
        id: 'list_view_captionbar',
      },
    ],
    codeName: 'usr0103274907',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'list_view列表视图布局面板',
    appDataEntityId: 'plmweb.comment',
    controlParam: {},
    modelId: 'ec74278f1f5a797ebc942e090298d91c',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0103274907',
  },
  title: '评论列表视图',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'eac2aa8e4fe80453d257341ab278a79a',
  modelType: 'PSAPPDEVIEW',
  name: 'commentlist_view',
  id: 'plmweb.comment_list_view',
};
