export default {
  mdctrlActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'tree',
  loadDefault: true,
  deviewCodeName: 'pc_customer_pickup_tree_view',
  deviewId: '158cadcc34c48526f2db11948c3203c4',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.CUSTOMER',
  },
  caption: '选择客户',
  codeName: 'customer_pc_customer_pickup_tree_view',
  appDataEntityId: 'plmweb.customer',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupTreeView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'n_owner_id_eq',
      value: 'product',
      id: 'n_owner_id_eq',
    },
    {
      rawValue: true,
      key: 'n_owner_type_eq',
      value: 'customer',
      id: 'n_owner_type_eq',
    },
    {
      key: 'product_id',
      value: 'product',
      id: 'product_id',
    },
  ],
  controls: [
    {
      detreeNodeRSs: [
        {
          childDETreeNodeId: 'customer_group',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 客户分组',
        },
        {
          childDETreeNodeId: 'customer',
          navigateParams: [
            {
              key: 'n_categories_like',
              value: 'ID',
              id: 'n_categories_like',
            },
          ],
          parentDETreeNodeId: 'ungrouped_type',
          parentValueLevel: 1,
          searchMode: 3,
          id: '未分组类型 - 客户',
        },
        {
          childDETreeNodeId: 'customer_type',
          parentAppDEFieldId: 'section_id',
          parentDER1N: {
            masterRS: 32,
            pickupDEFName: 'SECTION_ID',
            removeActionType: 2,
            codeName: 'section',
            dertype: 'DER1N',
            logicName: '分组-类别',
            minorCodeName: 'section_categories',
            minorServiceCodeName: 'section_categories',
            orderValue: 100,
            serviceCodeName: 'section',
            name: 'DER1N_CATEGORY_SECTION_SECTION_ID',
            id: 'base.category.der1n_category_section_section_id',
          },
          parentDETreeNodeId: 'customer_group',
          parentValueLevel: 1,
          searchMode: 3,
          id: '客户分组 - 客户类型',
        },
        {
          childDETreeNodeId: 'customer',
          navigateParams: [
            {
              key: 'n_categories_like',
              value: 'ID',
              id: 'n_categories_like',
            },
          ],
          parentDETreeNodeId: 'customer_type',
          parentValueLevel: 1,
          searchMode: 3,
          id: '客户类型 - 客户',
        },
        {
          childDETreeNodeId: 'ungrouped_type',
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 未分组类型',
        },
        {
          childDETreeNodeId: 'typeless_customer',
          navigateParams: [
            {
              key: 'n_categories_isnull',
              value: 'true',
              rawValue: true,
              id: 'n_categories_isnull',
            },
          ],
          parentDETreeNodeId: 'root',
          parentValueLevel: 1,
          searchMode: 3,
          id: '默认根节点 - 无类型客户',
        },
      ],
      detreeNodes: [
        {
          nodeValue: 'root',
          text: '默认根节点',
          nodeType: 'ROOT',
          treeNodeType: 'STATIC',
          hasDETreeNodeRSs: true,
          rootNode: true,
          name: '默认根节点',
          id: 'root',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'customer',
          appDataEntityId: 'plmweb.customer',
          treeNodeType: 'DE',
          name: '客户',
          id: 'customer',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          leafFlagAppDEFieldId: 'is_leaf',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'customer_group',
          appDataEntityId: 'plmweb.section',
          sysImage: {
            cssClass: 'fa fa-users',
            glyph: 'xf0c0@FontAwesome',
          },
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          expanded: true,
          name: '客户分组',
          id: 'customer_group',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_default',
          textAppDEFieldId: 'name',
          nodeType: 'customer_type',
          appDataEntityId: 'plmweb.category',
          sysImage: {
            cssClass: 'fa fa-user',
            glyph: 'xf007@FontAwesome',
          },
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          enableCheck: true,
          expanded: true,
          name: '客户类型',
          id: 'customer_type',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_normal',
          textAppDEFieldId: 'name',
          nodeType: 'typeless_customer',
          appDataEntityId: 'plmweb.customer',
          treeNodeType: 'DE',
          name: '无类型客户',
          id: 'typeless_customer',
        },
        {
          dataSourceType: 'DEDATASET',
          idAppDEFieldId: 'id',
          appDEDataSetId: 'fetch_no_section',
          textAppDEFieldId: 'name',
          nodeType: 'ungrouped_type',
          appDataEntityId: 'plmweb.category',
          sysImage: {
            cssClass: 'fa fa-user',
            glyph: 'xf007@FontAwesome',
          },
          treeNodeType: 'DE',
          hasDETreeNodeRSs: true,
          disableSelect: true,
          enableCheck: true,
          expanded: true,
          name: '未分组类型',
          id: 'ungrouped_type',
        },
      ],
      outputIconDefault: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.customer',
        id: 'create',
      },
      fetchControlAction: {
        appDataEntityId: 'plmweb.customer',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.customer',
        id: 'load',
      },
      dedataImportId: 'import_customer',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.customer',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.customer',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'pc_customer_pickup_tree_view_tree_view',
      controlType: 'TREEVIEW',
      logicName: '客户选择树视图（PC端）_树视图',
      appDataEntityId: 'plmweb.customer',
      controlParam: {
        id: 'tree',
      },
      modelId: 'ecb7015064561695f75abc2e68926fc9',
      modelType: 'PSDETREEVIEW',
      name: 'tree',
      id: 'plmweb.customer.pc_customer_pickup_tree_view_tree_view',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.customer',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.CUSTOMER',
      },
      caption: '选择客户',
      codeName: 'pc_customer_pickup_tree_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.customer',
      controlParam: {},
      name: 'captionbar',
      id: 'pc_customer_pickup_tree_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPTREEVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.customer',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '客户选择树视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPTREEVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2ba59c895428d46814aeabb0419f0832',
  modelType: 'PSAPPDEVIEW',
  name: 'customerpc_customer_pickup_tree_view',
  id: 'plmweb.customer_pc_customer_pickup_tree_view',
};
