export default {
  gridRowActiveMode: 1,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'not_add_pick_up_grid_view_review',
  deviewId: '8B35ECE3-F519-4698-B15C-8525557B6D74',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IDEA',
  },
  caption: '需求',
  codeName: 'idea_not_add_pick_up_grid_view_review',
  appDataEntityId: 'plmweb.idea',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'title',
              editor: {
                editorType: 'TEXTBOX',
                placeHolder: '请输入需求标题',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_title_like',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.IDEA.N_TITLE_LIKE',
              },
              caption: '标题',
              codeName: 'n_title_like',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colMD: 5,
                layout: 'TABLE_24COL',
              },
              id: 'n_title_like',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'state',
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.prodmgmt__idea_state',
                editorType: 'DROPDOWNLIST',
                placeHolder: '请选择需求状态',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_state_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.IDEA.N_STATE_EQ',
              },
              caption: '状态',
              codeName: 'n_state_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colMD: 5,
                layout: 'TABLE_24COL',
              },
              id: 'n_state_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'idea_type',
              editor: {
                singleSelect: true,
                appCodeListId: 'plmweb.projmgmt__requirement_type',
                editorType: 'DROPDOWNLIST',
                placeHolder: '请选择需求类型',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_idea_type_eq',
              },
              allowEmpty: true,
              needCodeListConfig: true,
              caption: '需求类型',
              codeName: 'n_idea_type_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colMD: 5,
                layout: 'TABLE_24COL',
              },
              id: 'n_idea_type_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'NONE',
              noPrivDisplayMode: 1,
              appDEFieldId: 'assignee_name',
              editor: {
                singleSelect: true,
                handlerType: 'PickupText',
                appDEACModeId: 'default',
                appDEDataSetId: 'fetch_default',
                appDataEntityId: 'plmweb.user',
                enableAC: true,
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'n_assignee_id_eq',
                editorParams: {
                  'SRFNAVPARAM.n_department_id_eq': '%srforgsectorid%',
                  AC: 'TRUE',
                  'SRFNAVPARAM.n_status_eq': '1',
                  TRIGGER: 'TRUE',
                  URL: 'products/${context.product}/product_members/fetch_default',
                  PICKUPVIEW: 'FALSE',
                  USERMETHOD: 'post',
                  USERMAP: '{"id":"user_id","name":"name"}',
                  DEPTMAP: '{"id":"id","name":"display_name"}',
                  DEPTMETHOD: 'get',
                  DEPTURL: '/users/fetch_default',
                },
                editorStyle: 'PERSONEL_SELECT_PRODUCT',
                editorType: 'PICKEREX_TRIGGER',
                editorItems: [
                  {
                    id: 'n_assignee_id_eq',
                  },
                ],
                sysPFPluginId: 'person_select',
                placeHolder: '负责人',
                valueType: 'SIMPLE',
                editable: true,
                navigateParams: [
                  {
                    key: 'n_department_id_eq',
                    value: 'srforgsectorid',
                    id: 'n_department_id_eq',
                  },
                  {
                    key: 'n_status_eq',
                    value: '1',
                    rawValue: true,
                    id: 'n_status_eq',
                  },
                ],
                id: 'n_assignee_name_eq',
              },
              allowEmpty: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.IDEA.N_ASSIGNEE_NAME_EQ',
              },
              caption: '负责人',
              codeName: 'n_assignee_name_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colMD: 5,
                layout: 'TABLE_24COL',
              },
              id: 'n_assignee_name_eq',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'assignee_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'n_assignee_id_eq',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFSFITEM.IDEA.N_ASSIGNEE_ID_EQ',
              },
              caption: '负责人',
              codeName: 'n_assignee_id_eq',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colLG: 5,
                colMD: 5,
                layout: 'TABLE_24COL',
              },
              id: 'n_assignee_id_eq',
            },
          ],
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'review_searchform',
      controlType: 'SEARCHFORM',
      logicName: '评审搜索表单',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'F8947DD9-3D16-4F0E-AEDF-7E2C6F10C355',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'plmweb.idea.review_searchform',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'identifier',
          excelCaption: '编号',
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.IDEA.IDENTIFIER',
          },
          caption: '编号',
          codeName: 'identifier',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'identifier',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.TITLE',
          },
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'title',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'state',
          excelCaption: '状态',
          appCodeListId: 'plmweb.prodmgmt__idea_state',
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.STATE',
          },
          caption: '状态',
          codeName: 'state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'state',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'review_result_state',
          excelCaption: '评审结果',
          appCodeListId: 'plmweb.testmgmt__review_result',
          appDEFieldId: 'review_result_state',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '评审结果',
          codeName: 'review_result_state',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'review_result_state',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'idea_type',
          excelCaption: '需求类型',
          appCodeListId: 'plmweb.projmgmt__requirement_type',
          appDEFieldId: 'idea_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '需求类型',
          codeName: 'idea_type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'idea_type',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'priority',
          excelCaption: '优先级',
          appCodeListId: 'plmweb.prodmgmt__idea_priority',
          appDEFieldId: 'priority',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PRIORITY',
          },
          caption: '优先级',
          codeName: 'priority',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'priority',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'assignee_name',
          excelCaption: '负责人',
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ASSIGNEE_NAME',
          },
          caption: '负责人',
          codeName: 'assignee_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'assignee_name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'identifier',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'identifier',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'state',
        },
        {
          appDEFieldId: 'review_result_state',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'review_result_state',
        },
        {
          appDEFieldId: 'idea_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'idea_type',
        },
        {
          appDEFieldId: 'priority',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'priority',
        },
        {
          appDEFieldId: 'assignee_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'assignee_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'assignee_id',
        },
        {
          appDEFieldId: 'product_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'product_id',
        },
        {
          appDEFieldId: 'category_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'category_id',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmstag',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_review_data',
        appDataEntityId: 'plmweb.idea',
        id: 'fetch',
      },
      dedataImportId: 'import_idea',
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.idea',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'not_check_pickup_grid_review',
      controlType: 'GRID',
      logicName: '未选择的需求选择表格（评审）',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'grid',
      },
      modelId: '1c2db98ed5e0dc83683aef35ec23615b',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'plmweb.idea.not_check_pickup_grid_review',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'plmweb.idea',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IDEA',
      },
      caption: '需求',
      codeName: 'not_add_pick_up_grid_view_review_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.idea',
      controlParam: {},
      name: 'captionbar',
      id: 'not_add_pick_up_grid_view_review_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.idea',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '未添加的需求表格',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '9464b3736d3ebda075a0df2a45011724',
  modelType: 'PSAPPDEVIEW',
  name: 'ideanot_add_pick_up_grid_view_review',
  id: 'plmweb.idea_not_add_pick_up_grid_view_review',
};
