export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'advanced_setting_edit_view',
  deviewId: '3fb39ba4967a0cd8a84106fc43cd146a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.LIBRARY',
  },
  caption: '高级设置',
  codeName: 'library_advanced_setting_edit_view',
  appDataEntityId: 'plmweb.library',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      autoSaveMode: 1,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.library',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.library',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.library',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.library',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.library',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.library',
        id: 'update',
      },
      enableAutoSave: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  rawItem: {
                    caption:
                      '如果要变更测试库的所属关系及可见范围，你可以移动它。移动后不影响测试库下的计划、用例、评审和报表。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem1',
                  },
                  codeName: 'rawitem1',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem1',
                },
                {
                  actionType: 'UIACTION',
                  buttonStyle: 'DEFAULT',
                  uiactionId: 'move_library@library',
                  tooltip: '移动测试库',
                  uiactionTarget: 'SINGLEKEY',
                  caption: '移动测试库',
                  codeName: 'button1',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    colLG: 2,
                    colMD: 2,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'button1',
                },
              ],
              caption: '移动测试库',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'group1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  rawItem: {
                    caption:
                      '如果此测试库已经结束了，你可以归档它。归档后如果想重新使用该测试库，可以通过配置中心由管理员进行激活。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem2',
                  },
                  codeName: 'rawitem2',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem2',
                },
                {
                  actionType: 'UIACTION',
                  buttonStyle: 'DEFAULT',
                  uiactionId: 'archive@library',
                  tooltip: '归档测试库',
                  uiactionTarget: 'SINGLEKEY',
                  caption: '归档测试库',
                  codeName: 'button2',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    colLG: 2,
                    colMD: 2,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'button2',
                },
              ],
              caption: '归档测试库',
              codeName: 'grouppanel1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel1',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  rawItem: {
                    caption:
                      '如果此测试库已经不再需要了，你可以删除它。删除后如果想找回测试库，可以通过配置中心由管理员进行恢复。',
                    halign: 'LEFT',
                    valign: 'MIDDLE',
                    wrapMode: 'NOWRAP',
                    contentType: 'RAW',
                    id: 'rawitem3',
                  },
                  codeName: 'rawitem3',
                  detailStyle: 'DEFAULT',
                  detailType: 'RAWITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'rawitem3',
                },
                {
                  actionType: 'UIACTION',
                  buttonStyle: 'DEFAULT',
                  uiactionId: 'delete@library',
                  tooltip: '删除测试库',
                  uiactionTarget: 'SINGLEKEY',
                  caption: '删除测试库',
                  codeName: 'button3',
                  detailStyle: 'DEFAULT',
                  detailType: 'BUTTON',
                  layoutPos: {
                    colLG: 2,
                    colMD: 2,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'delete-button',
                  },
                  showCaption: true,
                  id: 'button3',
                },
              ],
              caption: '删除测试库',
              codeName: 'grouppanel2',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel2',
            },
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '测试用例执行失败，是否自动触发缺陷工作项。',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem4',
                      },
                      codeName: 'rawitem4',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'rawitem4',
                    },
                    {
                      rawItem: {
                        content:
                          '<p><span style="font-size: 8pt; color: #e03e2d;">温馨提示：测试计划需绑定项目后，此配置才会生效</span></p>',
                        contentType: 'HTML',
                        id: 'rawitem5',
                      },
                      codeName: 'rawitem5',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'rawitem5',
                    },
                  ],
                  codeName: 'grouppanel4',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 4,
                    colMD: 4,
                    layout: 'TABLE_24COL',
                  },
                  sysCss: {
                    cssName: 'library_setting_style',
                  },
                  id: 'grouppanel4',
                },
                {
                  buildInActions: 2,
                  contentType: 'REPEATER',
                  fieldName: 'run_parameter',
                  appDEFieldId: 'run_parameter',
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'val',
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'SWITCH',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'val',
                      },
                      allowEmpty: true,
                      caption: '是否开启自动创建缺陷',
                      codeName: 'val',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'val',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'id',
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'parameter_id',
                      },
                      allowEmpty: true,
                      hidden: true,
                      caption: '参数标识',
                      codeName: 'parameter_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'parameter_id',
                    },
                    {
                      createDV: 'library',
                      createDVT: 'APPDATA',
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'owner_id',
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'owner_id',
                      },
                      updateDV: 'library',
                      updateDVT: 'APPDATA',
                      allowEmpty: true,
                      hidden: true,
                      caption: '所属标识',
                      codeName: 'owner_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'owner_id',
                    },
                    {
                      createDV: 'LIBRARY',
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'owner_type',
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'owner_type',
                      },
                      updateDV: 'LIBRARY',
                      allowEmpty: true,
                      hidden: true,
                      caption: '所属类型',
                      codeName: 'owner_type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'owner_type',
                    },
                    {
                      createDV: 'LIBRARY_RUNFAILURE',
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'owner_subtype',
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'owner_subtype',
                      },
                      updateDV: 'LIBRARY_RUNFAILURE',
                      allowEmpty: true,
                      hidden: true,
                      caption: '所属对象子类型',
                      codeName: 'owner_subtype',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      repeatContent: true,
                      id: 'owner_subtype',
                    },
                  ],
                  codeName: 'run_parameter',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colLG: 20,
                    colMD: 20,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'run_parameter',
                },
              ],
              caption: '配置参数',
              codeName: 'grouppanel3',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'grouppanel3',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '高级设置',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'advanced_setting',
      controlType: 'FORM',
      logicName: '高级设置',
      appDataEntityId: 'plmweb.library',
      controlLogics: [
        {
          eventNames: 'onLoadSuccess',
          logicTag: 'form',
          logicType: 'SCRIPT',
          scriptCode: "console.log('ctrl', ctrl);",
          triggerType: 'CTRLEVENT',
          id: 'loadsuccess',
        },
      ],
      controlParam: {
        id: 'form',
      },
      modelId: 'c8dc2e0eb532be5f81f0ef3ed390fefe',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.library.advanced_setting',
    },
    {
      codeName: 'advanced_setting_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'advanced_setting_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.LIBRARY',
      },
      caption: '高级设置',
      codeName: 'advanced_setting_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.library',
      controlParam: {},
      name: 'captionbar',
      id: 'advanced_setting_edit_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.library',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '高级设置',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '28dc893a8ce6dd3d6abb33795fa19250',
  modelType: 'PSAPPDEVIEW',
  name: 'libraryadvanced_setting_edit_view',
  id: 'plmweb.library_advanced_setting_edit_view',
};
