export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'idea_set_category_option_view',
  deviewId: '9bfd4f339d557f6ace193a2ecc887b04',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REVIEW',
  },
  caption: '设置类别',
  codeName: 'review_idea_set_category_option_view',
  height: 200,
  appDataEntityId: 'plmweb.review',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.review',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.review',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.review',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'plmweb.review',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.review',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'plmweb.review',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'categories_name',
              editor: {
                dropDownView: true,
                enablePickupView: true,
                singleSelect: true,
                pickupAppViewId: 'plmweb.review_idea_pick_up_tree_view',
                handlerType: 'PickupText',
                forceSelection: true,
                showTrigger: true,
                valueItemName: 'categories',
                editorParams: {
                  DROPDOWNVIEW: 'TRUE',
                  AC: 'FALSE',
                  TRIGGER: 'TRUE',
                  PICKUPVIEW: 'TRUE',
                },
                editorType: 'PICKEREX_DROPDOWNVIEW',
                editorItems: [
                  {
                    id: 'categories',
                  },
                ],
                placeHolder: '请选择类别',
                valueType: 'SIMPLE',
                editable: true,
                id: 'categories_name',
              },
              allowEmpty: true,
              caption: '类别',
              codeName: 'categories_name',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'categories_name',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'categories',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'categories',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.REVIEW.CATEGORIES',
              },
              caption: '类别',
              codeName: 'categories',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'categories',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'idea_set_category_form',
      controlType: 'FORM',
      logicName: '需求设置类别表单',
      appDataEntityId: 'plmweb.review',
      controlParam: {
        id: 'form',
      },
      modelId: '6c58c4ec73c6f63c8846fcc6450a3000',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.review.idea_set_category_form',
    },
    {
      codeName: 'idea_set_category_option_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.review',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'idea_set_category_option_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REVIEW',
      },
      caption: '设置类别',
      codeName: 'idea_set_category_option_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.review',
      controlParam: {},
      name: 'captionbar',
      id: 'idea_set_category_option_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.review',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '设置类别',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 400,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd63033628a0c3dd7fdd45d77824586d1',
  modelType: 'PSAPPDEVIEW',
  name: 'reviewidea_set_category_option_view',
  id: 'plmweb.review_idea_set_category_option_view',
};
