export default {
  getDataAppDEActionId: 'get_redirect_data',
  redirectAppViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '评审编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.EDITVIEW',
      },
      refAppViewId: 'plmweb.review_edit_view',
      name: 'REVIEW:EDITVIEW',
      id: 'review:editview',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '评审编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.EDITVIEW',
      },
      refAppViewId: 'plmweb.review_edit_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  typeAppDEFieldId: 'type',
  enableCustomGetDataAction: true,
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: 'b39b83b4ff0b5681858314d954836f0e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.REVIEW',
  },
  caption: '评审',
  codeName: 'review_redirect_view',
  appDataEntityId: 'plmweb.review',
  appViewRefs: [
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '评审主视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.MAIN_VIEW',
      },
      refAppViewId: 'plmweb.review_main_view',
      name: 'TEST_CASE',
      id: 'test_case',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '评审主视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.MAIN_VIEW',
      },
      refAppViewId: 'plmweb.review_page_main_view',
      name: 'PAGE',
      id: 'page',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '评审主视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.MAIN_VIEW',
      },
      refAppViewId: 'plmweb.review_idea_main_view',
      name: 'IDEA',
      id: 'idea',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '评审主视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.REVIEW.MAIN_VIEW',
      },
      refAppViewId: 'plmweb.review_work_item_main_view',
      name: 'WORK_ITEM',
      id: 'work_item',
    },
  ],
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.REVIEW',
      },
      caption: '评审',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.review',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.review',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '评审数据重定向视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.REVIEW.REDIRECTVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: 'ba758194e9adfdc4c18bab9a6b999429',
  modelType: 'PSAPPDEVIEW',
  name: 'reviewRedirectView',
  id: 'plmweb.review_redirect_view',
};
