export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'idea_create_wizard_view',
  deviewId: '8db83871286097d0d4d1e114c8122f64',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'PAGE.CAPTION.REVIEW.CREATE_WIZARD_VIEW',
  },
  caption: '新建评审',
  codeName: 'review_wizard_idea_create_wizard_view',
  height: 720,
  appDataEntityId: 'plmweb.review_wizard',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'WizardView',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'PRINCIPAL_TYPE',
      value: 'idea',
      name: 'PRINCIPAL_TYPE',
      id: 'principal_type',
    },
    {
      rawValue: true,
      key: 'TARGET_TYPE',
      value: 'review',
      name: 'TARGET_TYPE',
      id: 'target_type',
    },
  ],
  appViewParams: [
    {
      key: 'SRFRENEWSESSION',
      value: 'true',
      name: 'SRFRENEWSESSION',
      id: 'srfrenewsession',
    },
  ],
  controls: [
    {
      finishControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.review_wizard',
        id: 'finish',
      },
      initControlAction: {
        appDEMethodId: 'createtemp',
        appDataEntityId: 'plmweb.review_wizard',
        id: 'init',
      },
      deeditForms: [
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'plmweb.review_wizard',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'plmweb.review_wizard',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'fill_info',
            deformName: '需求新建表单',
            dewizardStepId: '评审信息',
            stepActions: ['NEXT'],
            stepTag: 'fill_info',
            firstForm: true,
            id: 'fill_info',
          },
          formFuncMode: 'WIZARDFORM',
          deformItemUpdates: [
            {
              codeName: 'fill_guideline',
              appDEMethodId: 'fill_guideline',
              defiupdateDetails: [
                {
                  id: 'review_stage',
                },
                {
                  id: 'review_guideline_id',
                },
              ],
              showBusyIndicator: true,
              id: 'fill_guideline',
            },
          ],
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'name',
                      editor: {
                        maxLength: 200,
                        editorType: 'TEXTBOX',
                        placeHolder: '输入标题',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'review_name',
                      },
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW.CREATE_FORM.FORMITEM.NAME',
                      },
                      caption: '标题',
                      codeName: 'review_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'review_name',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          itemHeight: 450,
                          labelPos: 'NONE',
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'description',
                          editor: {
                            editorHeight: 450,
                            editorParams: {
                              USERINSCRIPT:
                                'value.replaceAll(/\\@\\{\\"(user)?id\\":\\"(.+?)\\",\\"name\\":\\"(.+?)\\"\\}/g,(x, user, id, name) => {return controller.getNodeInfo({ id, name })}).replaceAll(/\\@\\{userid=(.+?),name=(.+?)\\}/g,(x, id, name) => {return controller.getNodeInfo({ id, name })})',
                              MAXHEIGHT: '450',
                              QUOTECODELISTMAP:
                                '{"type":"plmweb.base__recent_visite"}',
                              QUOTEFIELDMAP:
                                '{"identifier":"show_identifier","name":"name","id":"id","owner_subtype":"owner_subtype","owner_id":"owner_id","owner_type":"owner_type","recent_parent":"recent_parent"}',
                              QUOTEPARAMS: '{"sort":"update_time,desc"}',
                              MODE: 'default',
                              QUOTEINSCRIPT:
                                'value.replaceAll(/\\#\\{(\\".+?\\":\\".+?\\")(,\\"icon\\":\\"((.|[\\t\\r\\f\\n\\s])+?)\\")*\\}/g,(x, value, icon) => { const item = JSON.parse("{" + value + "}"); if (icon) { icon = icon.slice(8).slice(1, -1); } return controller.getNodeInfo({ icon, ...item })})',
                              USERSCRIPT:
                                '`@{"id":"${data.id}","name":"${data.name}"}`',
                              QUOTESCRIPT:
                                '`#{"id":"${data.id}","name":"${data.name}","identifier":"${data.identifier}","owner_id":"${data.owner_id}","owner_type":"${data.owner_type}","owner_subtype":"${data.owner_subtype}","recent_parent":"${data.recent_parent}"}`',
                              USERURL:
                                "`${context.library ? `libraries/${context.library}/library_members/fetch_default` : context.product ? `products/${context.product}/product_members/fetch_default` : context.project ? `projects/${context.project}/project_members/fetch_default` : context.discuss_topic? `discuss_topics/${context.discuss_topic}/discuss_members/fetch_default` : ''}`",
                              USERFIELDMAP: '{"id":"user_id","name":"name"}',
                              INSERTKEYS:
                                '[{"index":66,"keys":["marker"]},{"index":5,"keys":["paintformat"]}]',
                              QUOTEURL: '`recents/fetch_recent_access`',
                            },
                            editorStyle: 'COLLAPSE',
                            editorType: 'HTMLEDITOR',
                            sysPFPluginId: 'comment',
                            placeHolder: '输入描述',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'description',
                          },
                          allowEmpty: true,
                          emptyCaption: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.REVIEW.CREATE_FORM.FORMITEM.DESCRIPTION',
                          },
                          codeName: 'description',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          id: 'description',
                        },
                      ],
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW.CREATE_FORM.GROUPPANEL.GROUPPANEL3',
                      },
                      caption: '描述',
                      codeName: 'grouppanel3',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'grouppanel3',
                    },
                  ],
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 16,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'principal_name',
                      editor: {
                        singleSelect: true,
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_quick',
                        appDataEntityId: 'plmweb.product',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'principal_id',
                        editorParams: {
                          AC: 'TRUE',
                          TRIGGER: 'TRUE',
                          PICKUPVIEW: 'FALSE',
                        },
                        editorType: 'PICKEREX_TRIGGER',
                        editorItems: [
                          {
                            id: 'principal_id',
                          },
                        ],
                        placeHolder: '请选择所属产品',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'principal_name',
                      },
                      caption: '所属产品',
                      codeName: 'principal_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'principal_name',
                    },
                    {
                      createDV: 'product',
                      createDVT: 'APPDATA',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'principal_id',
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'principal_id',
                      },
                      updateDV: 'product',
                      updateDVT: 'APPDATA',
                      allowEmpty: true,
                      hidden: true,
                      caption: '产品标识',
                      codeName: 'principal_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'principal_id',
                    },
                    {
                      createDV: 'product',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'principal_type',
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'principal_type',
                      },
                      updateDV: 'product',
                      allowEmpty: true,
                      hidden: true,
                      caption: '产品类型',
                      codeName: 'principal_type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'principal_type',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'type',
                      deformItemUpdateId: 'fill_guideline',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'plmweb.testmgmt__review_type_guideline',
                        editorParams: {
                          'SRFNAVPARAM.N_SCOPE_ID_EQ': '%product%',
                        },
                        editorType: 'DROPDOWNLIST',
                        placeHolder: '选择评审类型',
                        valueType: 'SIMPLE',
                        editable: true,
                        navigateParams: [
                          {
                            key: 'n_scope_id_eq',
                            value: 'product',
                            id: 'n_scope_id_eq',
                          },
                        ],
                        id: 'type',
                      },
                      needCodeListConfig: true,
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW_WIZARD.CREATE_FORM.FORMITEM.TYPE',
                      },
                      caption: '评审类型',
                      codeName: 'type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'type',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      editor: {
                        dropDownView: true,
                        enablePickupView: true,
                        singleSelect: true,
                        pickupAppViewId: 'plmweb.review_idea_pick_up_tree_view',
                        forceSelection: true,
                        showTrigger: true,
                        valueItemName: 'categories',
                        editorParams: {
                          multiple: 'true',
                          DROPDOWNVIEW: 'TRUE',
                          AC: 'FALSE',
                          TRIGGER: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKEREX_DROPDOWNVIEW',
                        editorItems: [
                          {
                            navigateParams: [
                              {
                                key: 'n_owner_subtype_eq',
                                value: 'product_review',
                                rawValue: true,
                                id: 'n_owner_subtype_eq',
                              },
                              {
                                key: 'n_owner_id_eq',
                                value: 'product',
                                id: 'n_owner_id_eq',
                              },
                              {
                                key: 'n_owner_type_eq',
                                value: 'product',
                                rawValue: true,
                                id: 'n_owner_type_eq',
                              },
                            ],
                            id: 'categories',
                          },
                        ],
                        placeHolder: '选择类别',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'categories_name',
                      },
                      allowEmpty: true,
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW.CREATE_FORM.FORMITEM.CATEGORIES_NAME',
                      },
                      caption: '类别',
                      codeName: 'categories_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'categories_name',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      fieldName: 'guideline_id',
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'guideline_id',
                      editor: {
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'review_guideline_id',
                      },
                      resetItemNames: ['type'],
                      allowEmpty: true,
                      hidden: true,
                      capLanguageRes: {
                        lanResTag: 'DEF.LNAME.GUIDELINE_ID',
                      },
                      caption: '流程准则标识',
                      codeName: 'review_guideline_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'review_guideline_id',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          rawItem: {
                            content:
                              '<p><span style="color: rgb(249 57 31); font-family: SimSun; margin-right: 5px;">*</span>评审人</p>',
                            contentType: 'HTML',
                            id: 'rawitem1',
                          },
                          codeName: 'rawitem1',
                          detailStyle: 'DEFAULT',
                          detailType: 'RAWITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'rawitem1',
                        },
                        {
                          contentType: 'REPEATER',
                          appDEFieldId: 'stage',
                          resetItemNames: ['type'],
                          layout: {
                            columnCount: 24,
                            layout: 'TABLE_24COL',
                          },
                          deformDetails: [
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'NONE',
                              noPrivDisplayMode: 1,
                              editor: {
                                halign: 'LEFT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                editorType: 'SPAN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'name',
                              },
                              allowEmpty: true,
                              caption: '阶段名称',
                              codeName: 'name',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'name',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'NONE',
                              noPrivDisplayMode: 1,
                              editor: {
                                enablePickupView: true,
                                singleSelect: true,
                                enableAC: true,
                                forceSelection: true,
                                showTrigger: true,
                                valueItemName: 'reviewer',
                                editorParams: {
                                  TEAMMEMBERURL:
                                    '/groups/${params.teamid}/members/fetch_default',
                                  TEAMTYPEFIELD: 'reviewer_type',
                                  TEAMMETHOD: 'post',
                                  'SRFNAVPARAM.n_department_id_eq':
                                    '%srforgsectorid%',
                                  AC: 'TRUE',
                                  TEAMMEMBERMETHOD: 'post',
                                  TEAMURL: '/groups/fetch_default',
                                  'SRFNAVPARAM.n_status_eq': '1',
                                  URL: 'products/${context.product}/product_members/fetch_default',
                                  PICKUPVIEW: 'TRUE',
                                  USERMAP: '{"id":"user_id","name":"name"}',
                                  USERMETHOD: 'post',
                                  DEPTURL: '/users/fetch_default',
                                  DEPTMETHOD: 'get',
                                  DEPTMAP: '{"id":"id","name":"display_name"}',
                                },
                                editorStyle: 'IDEA_TEAM_SELECT',
                                editorType: 'PICKER',
                                sysPFPluginId: 'team_select',
                                valueType: 'SIMPLE',
                                editable: true,
                                navigateParams: [
                                  {
                                    key: 'n_department_id_eq',
                                    value: 'srforgsectorid',
                                    id: 'n_department_id_eq',
                                  },
                                  {
                                    key: 'n_status_eq',
                                    value: '1',
                                    rawValue: true,
                                    id: 'n_status_eq',
                                  },
                                ],
                                id: 'reviewer_name',
                              },
                              codeName: 'reviewer_name',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colLG: 12,
                                colMD: 12,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'reviewer_name',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'reviewer',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: '评审人',
                              codeName: 'reviewer',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'reviewer',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'stage_state',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: '阶段状态',
                              codeName: 'stage_state',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'stage_state',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'guideline_id',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: '流程准则',
                              codeName: 'guideline_id',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'guideline_id',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'id',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: 'ID',
                              codeName: 'id',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'id',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'order',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: '排序',
                              codeName: 'order',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'order',
                            },
                            {
                              dataType: 25,
                              enableCond: 3,
                              labelPos: 'LEFT',
                              labelWidth: 130,
                              noPrivDisplayMode: 1,
                              editor: {
                                editorType: 'HIDDEN',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'reviewer_type',
                              },
                              allowEmpty: true,
                              hidden: true,
                              caption: '评审人类型',
                              codeName: 'reviewer_type',
                              detailStyle: 'DEFAULT',
                              detailType: 'FORMITEM',
                              layoutPos: {
                                colMD: 24,
                                layout: 'TABLE_24COL',
                              },
                              repeatContent: true,
                              id: 'reviewer_type',
                            },
                          ],
                          codeName: 'review_stage',
                          detailStyle: 'DEFAULT',
                          detailType: 'MDCTRL',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'review_stage',
                        },
                      ],
                      caption: '评审人',
                      codeName: 'grouppanel4',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      defdgroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedDetailNames: ['type'],
                          groupOP: 'AND',
                          defdlogics: [
                            {
                              condOP: 'ISNOTNULL',
                              defdname: 'type',
                              logicType: 'SINGLE',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel4',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'TOP',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'categories',
                      editor: {
                        editorParams: {
                          'srfnavparam.n_owner_subtype_eq': 'product_review',
                          'srfnavparam.n_owner_id_eq': '%product%',
                          'srfnavparam.n_owner_type_eq': 'product',
                        },
                        editorType: 'HIDDEN',
                        valueType: 'SIMPLE',
                        editable: true,
                        navigateParams: [
                          {
                            key: 'n_owner_subtype_eq',
                            value: 'product_review',
                            rawValue: true,
                            id: 'n_owner_subtype_eq',
                          },
                          {
                            key: 'n_owner_id_eq',
                            value: 'product',
                            id: 'n_owner_id_eq',
                          },
                          {
                            key: 'n_owner_type_eq',
                            value: 'product',
                            rawValue: true,
                            id: 'n_owner_type_eq',
                          },
                        ],
                        id: 'categories',
                      },
                      allowEmpty: true,
                      hidden: true,
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW.CREATE_FORM.FORMITEM.CATEGORIES',
                      },
                      caption: '类别',
                      codeName: 'categories',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'categories',
                    },
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 21,
                          enableCond: 3,
                          labelPos: 'TOP',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'attentions',
                          editor: {
                            singleSelect: true,
                            handlerType: 'PickupText',
                            enableAC: true,
                            forceSelection: true,
                            showTrigger: true,
                            editorParams: {
                              MULTIPLE: 'true',
                              DEFAULTATNVALUE: '40',
                              'SRFNAVPARAM.n_department_id_eq':
                                '%srforgsectorid%',
                              AC: 'TRUE',
                              DEFAULTSELCURUSER: 'true',
                              'SRFNAVPARAM.n_status_eq': '1',
                              TRIGGER: 'TRUE',
                              SELFFILLMAP:
                                '{"user_id":"user_id","user_name":"name"}',
                              URL: 'products/${context.product}/product_members/fetch_default',
                              PICKUPVIEW: 'FALSE',
                              USERMETHOD: 'post',
                              USERMAP: '{"id":"user_id","name":"name"}',
                              DEPTMAP: '{"id":"id","name":"display_name"}',
                              DEPTMETHOD: 'get',
                              DEPTURL: '/users/fetch_default',
                            },
                            editorStyle: 'PERSONEL_SELECT_PRODUCT',
                            editorType: 'PICKEREX_TRIGGER',
                            objectIdField: 'id',
                            objectNameField: 'name',
                            sysPFPluginId: 'person_select',
                            valueType: 'OBJECTS',
                            editable: true,
                            navigateParams: [
                              {
                                key: 'n_department_id_eq',
                                value: 'srforgsectorid',
                                id: 'n_department_id_eq',
                              },
                              {
                                key: 'n_status_eq',
                                value: '1',
                                rawValue: true,
                                id: 'n_status_eq',
                              },
                            ],
                            id: 'attentions',
                          },
                          allowEmpty: true,
                          capLanguageRes: {
                            lanResTag:
                              'CONTROL.DEFORM.REVIEW.CREATE_FORM.FORMITEM.ATTENTIONS',
                          },
                          caption: '关注人',
                          codeName: 'attentions',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colMD: 24,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'attentions',
                        },
                      ],
                      capLanguageRes: {
                        lanResTag:
                          'CONTROL.DEFORM.REVIEW.CREATE_FORM.GROUPPANEL.GROUPPANEL5',
                      },
                      caption: '关注字段',
                      codeName: 'grouppanel5',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel5',
                    },
                  ],
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 8,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel2',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              capLanguageRes: {
                lanResTag: 'CONTROL.DEFORM.REVIEW.MAIN.FORMPAGE.FORMPAGE1',
              },
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'idea_create_form',
          controlType: 'FORM',
          logicName: '需求新建表单',
          appDataEntityId: 'plmweb.review_wizard',
          controlLogics: [
            {
              eventNames: 'onLoadSuccess',
              logicTag: 'wizardpanel_form_fill_info',
              logicType: 'APPDEUILOGIC',
              appDEUILogicId: 'remove_batch_temp',
              appDataEntityId: 'plmweb.review_wizard',
              triggerType: 'CTRLEVENT',
              id: 'logic',
            },
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_fill_info',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_fill_info',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_fill_info',
          },
          modelId: '0e090f7deb7f38139cea97c3bb9fb80e',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_fill_info',
          id: 'plmweb.review_wizard.idea_create_form',
        },
        {
          getControlAction: {
            appDEMethodId: 'gettemp',
            appDataEntityId: 'plmweb.review_wizard',
            id: 'load',
          },
          updateControlAction: {
            appDEMethodId: 'updatetemp',
            appDataEntityId: 'plmweb.review_wizard',
            id: 'update',
          },
          dewizardForm: {
            formTag: 'review_connect',
            deformName: '新建时规划通用表单',
            dewizardStepId: '评审内容',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'review_connect',
            id: 'review_connect',
          },
          formFuncMode: 'WIZARDFORM',
          deformPages: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  appViewId: 'plmweb.review_content_under_review_grid_view',
                  parentDataJO: {
                    srfparentdename: 'REVIEW_WIZARD',
                    SRFPARENTTYPE: 'CUSTOM',
                  },
                  codeName: 'druipart1',
                  detailStyle: 'DEFAULT',
                  detailType: 'DRUIPART',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'druipart1',
                },
                {
                  dataType: 21,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'attentions',
                  editor: {
                    editorType: 'HIDDEN',
                    objectIdField: 'id',
                    objectNameField: 'name',
                    valueType: 'OBJECTS',
                    editable: true,
                    id: 'attentions',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ATTENTIONS',
                  },
                  caption: '关注',
                  codeName: 'attentions',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'attentions',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'id',
                  editor: {
                    editorType: 'HIDDEN',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'id',
                  },
                  allowEmpty: true,
                  hidden: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.ID',
                  },
                  caption: '标识',
                  codeName: 'id',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'id',
                },
              ],
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.REVIEW.CREATE_RE_TEST_CASE_FORM.FORMPAGE.FORMPAGE1',
              },
              caption: '基本信息',
              codeName: 'formpage1',
              detailStyle: 'DEFAULT',
              detailType: 'FORMPAGE',
              id: 'formpage1',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          tabHeaderPos: 'TOP',
          noTabHeader: true,
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'create_common_form',
          controlType: 'FORM',
          logicName: '新建时规划通用表单',
          appDataEntityId: 'plmweb.review_wizard',
          controlLogics: [
            {
              eventNames: 'SAVE',
              logicTag: 'wizardpanel_form_review_connect',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formsave',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'wizardpanel_form_review_connect',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'wizardpanel_formload',
            },
          ],
          controlParam: {
            id: 'wizardpanel_form_review_connect',
          },
          modelId: 'f0902d087f7a34c1ea65d7526bc7253a',
          modelType: 'PSDEFORM_EDITFORM',
          name: 'wizardpanel_form_review_connect',
          id: 'plmweb.review_wizard.create_common_form',
        },
      ],
      dewizard: {
        codeName: 'idea_create_wizard',
        firstDEWizardFormId: 'fill_info',
        nextCaption: '下一步',
        dewizardForms: [
          {
            formTag: 'fill_info',
            deformName: '需求新建表单',
            dewizardStepId: '评审信息',
            stepActions: ['NEXT'],
            stepTag: 'fill_info',
            firstForm: true,
            id: 'fill_info',
          },
          {
            formTag: 'review_connect',
            deformName: '新建时规划通用表单',
            dewizardStepId: '评审内容',
            stepActions: ['PREV', 'FINISH'],
            stepTag: 'review_connect',
            id: 'review_connect',
          },
        ],
        dewizardSteps: [
          {
            stepTag: 'fill_info',
            title: '评审信息',
            id: '评审信息',
          },
          {
            stepTag: 'review_connect',
            title: '评审内容',
            id: '评审内容',
          },
        ],
        wizardStyle: 'DEFAULT',
        name: '需求评审新建向导',
        id: 'testmgmt.review_wizard.idea_create_wizard',
      },
      wizardStyle: 'DEFAULT',
      showActionBar: true,
      showStepBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'idea_create_wizard',
      controlType: 'WIZARDPANEL',
      logicName: '需求评审新建向导',
      appDataEntityId: 'plmweb.review_wizard',
      controlParam: {
        id: 'wizardpanel',
      },
      modelId: '6cea2502ead9164766a587d0ff705246',
      modelType: 'PSDEWIZARDPANEL',
      name: 'wizardpanel',
      id: 'plmweb.review_wizard.idea_create_wizard',
    },
    {
      capLanguageRes: {
        lanResTag: 'PAGE.CAPTION.REVIEW.CREATE_WIZARD_VIEW',
      },
      caption: '新建评审',
      codeName: 'idea_create_wizard_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.review_wizard',
      controlParam: {},
      name: 'captionbar',
      id: 'idea_create_wizard_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEWIZARDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.review_wizard',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '评审新建向导',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.REVIEW.CREATE_WIZARD_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEWIZARDVIEW',
  width: 1400,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd08bc9ce9542c12a872407ddaf41d14f',
  modelType: 'PSAPPDEVIEW',
  name: 'review_wizardidea_create_wizard_view',
  id: 'plmweb.review_wizard_idea_create_wizard_view',
};
