export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'forecast_quick_update_view',
  deviewId: '651a5012221da5cf4df25f3ca7517762',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORKLOAD',
  },
  caption: '修改预估工时',
  codeName: 'workload_forecast_quick_update_view',
  height: 850,
  appDataEntityId: 'plmweb.workload',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'plmweb.workload',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'plmweb.workload',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'plmweb.workload',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get_register_workload',
        appDataEntityId: 'plmweb.workload',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'plmweb.workload',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update_workload',
        appDataEntityId: 'plmweb.workload',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'duration_updateform',
          defiupdateDetails: [
            {
              id: 'remaining_workload',
            },
          ],
          scriptCode:
            "const _form = view.getController('form');\r\nconst _form_set = _form.details;\r\nvar form_data = _form.state.data;\r\nvar remaining_workload = form_data.remaining_workload;\r\nvar actual_workload = form_data.actual_workload;\r\nvar estimated_workload = form_data.estimated_workload;\r\nvar duration_workload = form_data.duration;\r\nvar duration = 0;\r\nvar actual = 0;\r\nvar estimated = 0;\r\nvar remaining = 0; // 剩余工时\r\nif(duration_workload){\r\n\tduration = Number(duration_workload);\r\n}\r\n// 已登记的预估工时\r\nif(estimated_workload){\r\n\testimated = Number(estimated_workload);\r\n}\r\n// 已登记的实际工时\r\nif(actual_workload){\r\n\tactual = Number(actual_workload);\r\n\t// 重置剩余工时\r\n\tremaining = estimated + duration - actual;\r\n\tif(remaining <= 0){\r\n\t\tremaining = 0;\r\n\t}\r\n} else {\r\n\tremaining = estimated + duration;\r\n}\r\n_form_set.remaining_workload.setDataValue(remaining);",
          customCode: true,
          showBusyIndicator: true,
          name: '时长表单项更新',
          id: 'duration_updateform',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 12,
                layout: 'TABLE_12COL',
              },
              deformDetails: [
                {
                  createDV: '产品需求',
                  dataType: 25,
                  fieldName: 'workload_kind',
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    contentType: 'RAW',
                    editorType: 'RAW',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'workload_kind',
                  },
                  updateDV: '产品需求',
                  allowEmpty: true,
                  caption: '事项类型',
                  codeName: 'workload_kind',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'workload_kind',
                },
                {
                  createDV: 'work_item_title',
                  createDVT: 'APPDATA',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    contentType: 'RAW',
                    editorType: 'RAW',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  updateDV: 'work_item_title',
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.NAME',
                  },
                  caption: '事项',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 6,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'duration',
                  deformItemUpdateId: 'duration_updateform',
                  editor: {
                    precision: 1,
                    editorParams: {
                      precision: '1',
                      minvalue: '0',
                    },
                    editorType: 'NUMBER',
                    placeHolder: '请添加工时',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'duration',
                  },
                  valueFormat: '#0.0',
                  caption: '工作时长',
                  codeName: 'duration',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'duration',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  editor: {
                    contentType: 'RAW',
                    editorType: 'RAW',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'estimated_workload',
                  },
                  allowEmpty: true,
                  caption: '已登记工时',
                  codeName: 'estimated_workload',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'estimated_workload',
                },
                {
                  createDVT: 'CURTIME',
                  dataType: 5,
                  enableCond: 3,
                  itemWidth: 131,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'register_date',
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD',
                    },
                    editorType: 'DATEPICKEREX_NOTIME',
                    editorWidth: 1,
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'register_date',
                  },
                  updateDVT: 'CURTIME',
                  valueFormat: 'YYYY-MM-DD',
                  caption: '登记日期',
                  codeName: 'register_date',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'register_date',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'TOP',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'type_name',
                  editor: {
                    singleSelect: true,
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'plmweb.workload_type',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'type_id',
                    editorParams: {
                      AC: 'TRUE',
                      TRIGGER: 'TRUE',
                      PICKUPVIEW: 'FALSE',
                    },
                    editorType: 'PICKEREX_TRIGGER',
                    editorItems: [
                      {
                        id: 'type_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'type_name',
                  },
                  allowEmpty: true,
                  caption: '工作类别',
                  codeName: 'type_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 6,
                    colMD: 6,
                    layout: 'TABLE_12COL',
                  },
                  showCaption: true,
                  id: 'type_name',
                },
              ],
              caption: '工时基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 21,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'description',
              editor: {
                editorType: 'HTMLEDITOR',
                valueType: 'SIMPLE',
                editable: true,
                id: 'description',
              },
              allowEmpty: true,
              caption: '工作说明',
              codeName: 'description',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              showCaption: true,
              id: 'description',
            },
            {
              createDV: 'principal_id',
              createDVT: 'APPDATA',
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'principal_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'principal_id',
              },
              updateDV: 'principal_id',
              updateDVT: 'APPDATA',
              allowEmpty: true,
              hidden: true,
              caption: '工时主体标识',
              codeName: 'principal_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'principal_id',
            },
            {
              createDV: 'ESTIMATED_WORKLOAD',
              dataType: 25,
              enableCond: 3,
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'category',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'category',
              },
              updateDV: 'ESTIMATED_WORKLOAD',
              allowEmpty: true,
              hidden: true,
              caption: '工时类别',
              codeName: 'category',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'category',
            },
            {
              dataType: 25,
              enableCond: 3,
              fieldName: 'remaining_workload',
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'remaining_workload',
              },
              allowEmpty: true,
              hidden: true,
              caption: '剩余工时',
              codeName: 'remaining_workload',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'remaining_workload',
            },
            {
              dataType: 25,
              enableCond: 3,
              fieldName: 'actual_workload',
              labelPos: 'TOP',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'actual_workload',
              },
              allowEmpty: true,
              hidden: true,
              caption: '实际工时',
              codeName: 'actual_workload',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'actual_workload',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'type_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'type_id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '类别',
              codeName: 'type_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'type_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'forecast_quick_update_form',
      controlType: 'FORM',
      logicName: '预估工时快速修改',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        id: 'form',
      },
      modelId: 'ce8927b1cf4d957fde711bfcfdb49cfe',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'plmweb.workload.forecast_quick_update_form',
    },
    {
      codeName: 'forecast_quick_update_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'plmweb.workload',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'forecast_quick_update_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.WORKLOAD',
      },
      caption: '修改预估工时',
      codeName: 'forecast_quick_update_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'plmweb.workload',
      controlParam: {},
      name: 'captionbar',
      id: 'forecast_quick_update_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'plmweb.workload',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '预估工时快速修改视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 800,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'b34e71a8f32679e6df5e65e12b5505fe',
  modelType: 'PSAPPDEVIEW',
  name: 'workloadforecast_quick_update_view',
  id: 'plmweb.workload_forecast_quick_update_view',
};
