export default {
  tabLayout: 'TOP',
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'tab_exp_view',
  deviewId: '2906fce6200ee61fc6d6268fec889d83',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.WORKLOAD',
  },
  caption: '工时',
  codeName: 'workload_tab_exp_view',
  appDataEntityId: 'plmweb.workload',
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'CATEGORY',
      value: 'ACTUAL_WORKLOAD',
      name: 'CATEGORY',
      id: 'category',
    },
  ],
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '标题栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_captionbar',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '分页导航',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabexppanel',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    rawItem: {
                      rawItemParams: [
                        {
                          key: 'routeattributekeys',
                          value: 'category',
                        },
                      ],
                      predefinedType: 'NAV_POS',
                      id: 'nav_pos',
                    },
                    caption: '导航区占位',
                    itemStyle: 'DEFAULT',
                    itemType: 'RAWITEM',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'nav_pos',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'view_content',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 0,
                  layout: 'FLEX',
                },
                id: 'view_tabexppanel_bottom',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container1',
          },
          {
            actionGroupExtractMode: 'ITEM',
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              layout: 'FLEX',
            },
            id: 'view_tabexppanel_right',
          },
        ],
        layout: {
          dir: 'row',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'TabExpView',
        id: 'engine',
      },
    ],
    controls: [
      {
        tabExpPageIds: ['calendar', 'log'],
        tabLayout: 'TOP',
        uniqueTag: 'workload_tab_exp_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '工时日历分页搜索视图',
            refAppViewId: 'plmweb.workload_tab_search_view',
            name: 'EXPITEM:calendar',
            id: 'expitem:calendar',
          },
          {
            realTitle: '工时日志表格视图',
            refAppViewId: 'plmweb.workload_log_grid_view',
            name: 'EXPITEM:log',
            id: 'expitem:log',
          },
        ],
        controls: [
          {
            caption: '工时日历',
            embeddedAppDEViewId: 'plmweb.workload_tab_search_view',
            codeName: 'tab_exp_view_calendar',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.workload',
            controlParam: {
              id: 'calendar',
            },
            modelId: '1a93673445538379ba10fd3b7a80c26a_calendar',
            modelType: 'PSVIEWPANEL',
            name: 'calendar',
            id: 'tab_exp_view_calendar',
          },
          {
            caption: '工时日志',
            embeddedAppDEViewId: 'plmweb.workload_log_grid_view',
            codeName: 'tab_exp_view_log',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'plmweb.workload',
            controlParam: {
              id: 'log',
            },
            modelId: '1a93673445538379ba10fd3b7a80c26a_log',
            modelType: 'PSVIEWPANEL',
            name: 'log',
            id: 'tab_exp_view_log',
          },
        ],
        codeName: 'tab_exp_view_tabexppanel',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'plmweb.workload',
        controlParam: {},
        modelId: '1a93673445538379ba10fd3b7a80c26a_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_exp_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.WORKLOAD',
        },
        caption: '工时',
        codeName: 'tab_exp_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'plmweb.workload',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_exp_view_captionbar',
      },
    ],
    codeName: 'usr0523312624',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'tab_exp_view分页导航视图布局面板',
    appDataEntityId: 'plmweb.workload',
    controlParam: {},
    modelId: '14718489-64B7-4DE1-A62C-5369D9D475CF',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0523312624',
  },
  title: '工时实体分页导航视图',
  viewStyle: 'DEFAULT',
  viewType: 'DETABEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1a93673445538379ba10fd3b7a80c26a',
  modelType: 'PSAPPDEVIEW',
  name: 'workloadtab_exp_view',
  id: 'plmweb.workload_tab_exp_view',
};
